### ISSUE TITLE
Scheduled Jobs initial run

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#1045]
When a new scheduled interval job is created it doesn't run until the interval has elapsed. This may be what the user wants, but it may not.

It would be good to have a "run immediately" options in the Optional Fields section when creating the job. If checked the job would be run once immediately upon creation.

**Comment by hazmat345** [comment]
Can confirm that interval jobs do not run immediately.

**Comment by hazmat345** [comment]
After thinking about this some more, maybe a "run now" button would be a better option here.

**Comment by scott-taubman** [comment]
Would this be necessary if we had the "Run Now" button mentioned in #1062?  That seems like it solves the problem in a more generally applicable fashion.

**Comment by scott-taubman** [comment]
We decided that this is redundant with #1062.  Closing this issue.
