### ISSUE TITLE
Routable Read Log Requests

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#1048]
Currently it's possible to read plugin logs from the system admin page, provided the plugins are storing their logs in a permanent way. However, this does not work if the plugin exists on a downstream garden.

It's complicated by the fact that it's really a request creation. So we should probably come up with a better way to incorporate "pre-forward" steps into the processing chain.

**Comment by TheBurchLog** [comment]
Not sure why we can't expand it to do this. BG makes a request for logs and that could be routed.

**Comment by TheBurchLog** [comment]
Released in 3.24.1
