### ISSUE TITLE
Shutdown when scheduler is waiting on jobs

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#1083]
The scheduler doesn't shut down cleanly when waiting on a job to finish.

**Comment by TheBurchLog** [comment]
Attempted to replicate. I made a scheduled job to run `sleeper` for 360 seconds. When the job started, I shutdown Beer Garden. It successfully shuts down the scheduler logic on the first attempt and doesn't have to use the force shutdown.
