### ISSUE TITLE
Event-driven file watcher / scheduler

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#109]
It would be useful to have the ability to watch a directory for new files and kick off a request **with the new file as a parameter** when it comes in.

There's still a debate whether this constitutes a 'scheduler' or 'event-driven' or 'streaming'. Possibly some combination of the three.

(Migrated from beer-garden/bartender#6)

**Comment by hazmat345** [comment]
Pretty sure this is what @SpecificallyGravity is working on, no?

**Comment by hazmat345** [comment]
So I thought this was possible, but I can't figure out how to get it to work.

**Comment by hazmat345** [comment]
It's currently possible to set up a trigger that executes a request when file events occur. However, I can't figure out how to configure a job to use the file that triggered the request as a parameter.

It seems like there's code present that would enable this, but I'm not sure if anything was added to the frontend. I'm not sure how we go about adding this as it kind of breaks the normal flow of configuring the request and *then* configuring the trigger.

**Comment by TheBurchLog** [comment]
Not sure how to support file injection into the parameters. File Trigger will have the file info in the metadata, but it utilizes file events the same as CRON/Trigger, an event to run the provided parameters.

**Comment by TheBurchLog** [comment]
Resolved by: https://github.com/beer-garden/beer-garden/pull/1570
