### ISSUE TITLE
Official docker builds

### ISSUE THREAD

**Issue by kgwhitmer** [beer-garden/beer-garden#11]
Official docker builds of all the bits would be awesome.

**Comment by loganasherjones** [comment]
We are working on this. Right now our plan is to:

* Split out all the projects into their separate git repositories
* Get things deployed to PyPi
* Get things on Docker hub
* Get our documentation up and running

**Comment by kgwhitmer** [comment]
Config via ENV settings would be a very nice too... :)
Please and thank you.

**Comment by loganasherjones** [comment]
This is already done. Documentation should be coming up soon.

**Comment by loganasherjones** [comment]
Docker builds can be found here: https://hub.docker.com/u/bgio/
