### ISSUE TITLE
Garden creation url encoding issues

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/beer-garden#1100]
We recently added url encoding in various spots to ensure that the frontend could make correct calls to the backend to retrieve gardens with non-alphanumeric characters in their name.

Unfortunately we appear to have inadvertantly added the url encoding to the garden creation call, which results in the POST data being encoded.  This results in the actual garden name being encoded, i.e. "g%40rden" rather than "g@rden".

Somewhat related, I also notice that the URL that you get directed to after creating a garden ends up being double-encoded.  Meaning that if I create a garden named "g@rden", I should be redirected to:

* `/admin/gardens/g%40rden/`

but instead get directed to:

* `/admin/gardens/g%2540rden/`

The `%` of the encoded `%40` is getting encoded again.

**Comment by Jake-Ross** [comment]
This issue looks like it's caused by PR #1082. Gardens created manually POSTing in a RestClient do not have this issue. Moving the URL decoding to the backend (after routing, before the garden creation) should fix this.
