### ISSUE TITLE
Garden Sync with incompatible systems

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#1101]
It looks like the following scenario results in a complete failure of the sync:

1. Parent and child are synced
2. Stop the parent garden so it doesn't receive updates from the child garden
2. A system is removed on the child
3. A "new" system with the same name+version, ~but different commands~, is created on the child. EDIT: The commands don't need to be different - just removing and re-adding the system (so it has a different ID)
4. Start the parent
4. Parent initiates a sync

The parent will attempt to update the "replaced" system definition but will fail because of the commands mismatch.

**Comment by scott-taubman** [comment]
I suggest that we start by seeing if we can do the simplest possible thing, which to me seems like it would be to just delete any systems not present during the garden sync before we go and create new ones. That is, if a system exists in the local DB for which there is no system with a matching id present in the sync data, delete that DB entry. Then after you've done that cleanup, proceed with the create / update of the remaining systems in the sync data.

I suggested we "start" with the above and see where it gets us. That strategy may not be viable for reasons that won't be clear until we explore it and even if it is viable it may not be the whole solution.

**Comment by jlrpnbbngtn** [comment]
> That strategy may not be viable for reasons that won't be clear until we explore it and even if it is viable it may not be the whole solution, which is why I suggest it as a _start_.

Seems like a reasonable jumping off point.
