### ISSUE TITLE
Make default garden configuration more explicit

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/beer-garden#1104]
Currently it is the case that garden configuration is loaded from a merging of settings that you have explicitly configured and the default values as defined in the config schema.  This behavior is and has the potential to be the source of great confusion.  Two examples:

1) The UI reads only the explicitly defined configuration on a garden when loading the garden configuration page.  This means that if, for instance, you have set hostname and port on the garden, but not defined "ssl_enabled" at all, the UI will render the "ssl_enabled" checkbox as unchecked, when in reality the default value for that (which is the value that will get used in the absence of explicit configuration) is True.

2) If a user had not defined a setting on their garden because the default was acceptable, and then for some reason we decide to change the default value, the user's garden configuration would then change through no fault or desire of their own.  We'll again use "ssl_enabled" as the example.  Let's say the default value were False and users had their gardens configured and working using that default.  If we then change the default to True to encourage better practices on the part of our users, all existing garden configurations that were relying on that default would break.  This seems likely to confuse and annoy people.

One approach that might solve both ends of this confusion is to write down the default connection_param configuration at garden creation time.  That is, load the default configs and then save them as explicit configuration for the garden.  From that point forward, the defaults would not need to get merged with the explicitly set values because all of the values would be explicitly set (to those defaults).  It would be nice, though not required, if this was the behavior any time configuration was saved, such that if new configuration was added the defaults for that new configuration would be recorded in the garden config the next time it got saved.

Worth noting is that the configuration that was causing the problem described in 1) above is actually on the brewtils side of things (shown [here](https://github.com/beer-garden/brewtils/blob/develop/brewtils/specification.py#L60)).  I'm not sure that the source is important, except that it probably makes it less of a good idea to just change that default value to False to clear up the immediate source of confusion.

**Comment by Jake-Ross** [comment]
For reference, the correct location of the 'default' garden configs (including the ssl_enabled example) seems to be [here](https://github.com/beer-garden/beer-garden/blob/734c5a5238fc235e158e2578d747fb100eb5743d/src/app/beer_garden/config.py#L708-L883), as it includes STOMP configs as well.
