### ISSUE TITLE
SchemaForm coupling

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#1108]
Currently we expose a capability that's strongly coupled to the UI AngularSchemaForm implementation in Brewtils. This was almost definitely a bad idea and should probably be deprecated to prepare for the new UI.

## Background
The "normal" way things work is this: brewtils uses info from various sources (mostly the `@command` and `@parameter` decorators) to construct a Command object. This is stored in the database and retrieved by the frontend UI. The UI then passes this Command definition to the angular-schema-form-builder, which constructs an ASF `schema` and an ASF `form`. ASF then uses the schema and form to render the UI widgets, do validation, and manage the models.

If you turn on `ui.debug_mode` in the Beergarden config, you can see the schema and form definitions on the "make a request" page.

## The problem
We currently allow you to specify an alternate schema and/or form for a Command. So if you understand the structure of what ASF is expecting, you can customize the "make a request" page in ways that aren't possible the "normal" way:

```python
@command(form=[{"key": "parameters.message", "readonly": True}])
@parameter(key="message", type="String", optional=False, nullable=False)
def echo_message_custom_form_as_list(self, message="Can't change me! Hahaha!"):
    return message
```

This results in a disabled control where the value cannot be changed.

## Discussion
Generally, it's nice to let power users customize the frontend if they're willing to take on the burden of figuring out how to make it happen. This gives them the tools they need to do what they want without the need to support every possible customization ASF supports inside of Beergarden.

However, this obviously ties us to the way that ASF builds and interprets these structures, which means that in order for things to continue to work with a new UI we would need to translate ASF-specific things into whatever way the new UI expects things to work. This isn't really feasible as the amount of effort required wouldn't be worth it.

I think the best way forward is to deprecate the `schema` and `form` parameter attributes. They can then be removed when the new UI is ready, removing the need to worry about supporting them past their useful life.

**Comment by scott-taubman** [comment]
@scott-taubman We should notify people that this will be deprecated at the same time we notify about python 2 support coming to an end.
