### ISSUE TITLE
Update version endpoint to reflect current state of project

### ISSUE THREAD

**Issue by jlrpnbbngtn** [beer-garden/beer-garden#1118]
`beer_garden/src/app/beer_garden/api/http/handlers/misc.py` has class `VersionHandler`, which is the handler for the version endpoint.

The return includes information about the brew-view and bartender versions in use, which is not appropriate for version 3.x of beer garden.

**Comment by scott-taubman** [comment]
Let's clean up the way the version info is communicated in the UI as well.  We assert that there are multiple "components" on the about page, but that's not true anymore.  There's presumably a better way to display the version number there that is clean and less misleading.  The whole component status box on that about page can go away too.
