### ISSUE TITLE
Move to custom executor

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#114]
After #10 is done, we will have a scheduler, but the execution is quite simple. We create a request. The APScheduler supports a "max_instances." We cannot support that without creating a custom executor that:

* Ensures that no more than X instances will get created of a job

See more information here:

https://apscheduler.readthedocs.io/en/latest/extending.html#custom-executors

**Comment by hazmat345** [comment]
I think either this situation has changed or the documentation is just unclear. While working on #209 I basically re-implemented the changes that @loganasherjones made earlier to remove `max_instances`. Based on my testing things seem to work as expected - if a job would be run that would exceed the maximum number of instances it doesn't run and a log is printed:

> 2019-06-07 15:39:21,747 - apscheduler.scheduler - WARNING - Execution of job "test (trigger: interval[0:00:05], next run at: 2019-06-07 19:39:21 UTC)" skipped: maximum number of running instances reached (1)

I think the confusion may come from the linked documentation on custom executors. I think what that documentation is saying is that any custom executor implementation *must* implement that functionality (basically, it must provide the functionality that the apscheduler-provided executors provide).

**Comment by hazmat345** [comment]
I think this is OBE, so I recommend closing.

**Comment by hazmat345** [comment]
This seems to be working as expected - closing.
