### ISSUE TITLE
Job Import API lacks validation

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/beer-garden#1178]
It appears that the job import endpoint will create jobs for possibly any valid json, even if it's not a valid job definition.  A bit more research needed into the exact cases where this happens and more details TBD.

**Comment by scott-taubman** [comment]
An easy way to reproduce this is to supply `[{}]` as the POST body.  A job entry with no name, trigger, etc will be created.

The right thing to do here is probably drop the custom logic in the `create_jobs` function in `scheduler.py` and just have it call `create_job` for every entry.  That should allow the model validation to do its thing.  We can circle back to the transaction (or transaction-like) behavior at some later point.

Note that there will probably be some updates to handler code to ensure that exceptions are handled properly and the right response code gets returned.

**Comment by scott-taubman** [comment]
A side note worth mentioning:  it looks like the response that comes back from the import endpoint doesn't actually match what's documented.  It's supposed to be:

```json
{ "ids": ["string"] }
```
And instead it looks like it's just:

```json
["string"]
```

**Comment by jlrpnbbngtn** [comment]
> A side note worth mentioning: it looks like the response that comes back from the import endpoint doesn't actually match what's documented. It's supposed to be:
> 
> ```json
> { "ids": ["string"] }
> ```
> 
> And instead it looks like it's just:
> 
> ```json
> ["string"]
> ```

Should be a new, different ticket with "low priority" tag. It's counterproductive to mix high-priority and low-priority issues into the same issue, IMO, even if they appear on the surface to be tangentially related.

**Comment by scott-taubman** [comment]
Every ticket incurs overhead.  Whoever tackles this one should just fix the endpoint.  Basically, both of these problems, the lack of validation and the wrong documentation are things that should have been caught in test / review and we failed to catch it.  If it had been caught then, whoever was working the originally issue would have been responsible for correcting both things.  I don't see any reason to split out the work now and further punish ourselves for the mistake.

**Comment by jlrpnbbngtn** [comment]
> ... don't see any reason to split out the work now and further punish ourselves for the mistake.
It reduces the cognitive load incurred while doing code reviews.
