### ISSUE TITLE
Improve type hinting

### ISSUE THREAD

**Issue by jlrpnbbngtn** [beer-garden/beer-garden#1183]
Catch-all ticket for found code in beer-garden that could benefit from type hints, but which is not (at the time of discovery) part of a pull request. This ticket is a WIP...

- [ ] https://github.com/beer-garden/beer-garden/blob/182e340e127a4d7dedfeb97c816fd8b8dec71edc/src/app/beer_garden/api/http/authentication/login_handlers/__init__.py#L4
- [ ] (69 issues) beer-garden/src/app/beer_garden/api/http/__init__.py
- [ ] https://github.com/beer-garden/beer-garden/blob/54ec10a4b44cf2f2836768bbd1b19c3aca42fc3a/src/app/beer_garden/api/http/base_handler.py#L227
- [ ] to be continued

**Comment by TheBurchLog** [comment]
This ticket would never end as code is developed. We will just have to do better at including type hinting.
