### ISSUE TITLE
Export Plugin

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#119]
From beer-garden/brew-view#7

We should be able to export a plugin as an egg or some kind of python package, this would be great because once you create a plugin you have the ability to export it.

In addition, if something is wrong with a plugin and you would like to troubleshoot it yourself without affecting an operational BEERGARDEN, it may be beneficial to export the plugin.

Some questions to consider:

    How does this work for remote plugins?
    Can we only do this for local plugins?
    What about GUI-developed plugins?
    What about docker-based plugins?

**Comment by scott-taubman** [comment]
This is unlikely to be tackled in the current iteration of BG and is solved by the current WIP design for new BG.  Closing for now.
