### ISSUE TITLE
Job Success/Fail count inaccurate for jobs tasked to child gardens

### ISSUE THREAD

**Issue by Jake-Ross** [beer-garden/beer-garden#1235]
Related to #1157 [(PR here)](https://github.com/beer-garden/beer-garden/pull/1233)

When a job on a parent garden is tasked to a request on a child garden, the success/fail counter is sometimes not incremented due to the scheduler only checking the request's status immediately after the request is forwarded. This means that sometimes the scheduler will check the child request's status when it is `IN_PROGRESS`, causing it to never actually check for a successful/failed request.

Note that this is a separate issue from #1225, as no exceptions are thrown that causes the counter to not increment.

## To recreate
- Create a job that uses a request from a child garden (requires [#1157](https://github.com/beer-garden/beer-garden/pull/1233))
- Let the job run a few times, comparing the logs in BG to the success/failure count in the UI. You should be able to see requests being run in the logs that are not reflected in the UI's count.

**Comment by TheBurchLog** [comment]
Counters were expanded and look to be handled better. Release was 3.24.0
