### ISSUE TITLE
List of nullable booleans

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#126]
From beer-garden/brew-view#15

Whenever a default is given for a multi parameter we interpret it as being intended for the array, rather than the array item. This causes some weirdness for a list of null-able Booleans: since there is no way to specify a default for the Boolean itself the initial value is null.

Null for a Boolean is not great because it looks exactly the same as false but will fail validation if the Boolean isn't null-able.

**Comment by TheBurchLog** [comment]
Same as #7
