### ISSUE TITLE
Allow for better descriptions of Multi parameters

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#14]
If a parameter is multi, this means that it can have multiple values associated with it. BEERGARDEN takes care of rendering this well enough, but we do not give the plugin developers enough control over what to call the individual items inside the array. For example, let's say I have a parameter called **`list_of_strings`** I would want the **`display_name`** for the **`list_of_strings`** parameter to be the **`List of Strings`** with a description like, "A list of strings to echo out." For each of the individual strings though, I want their **`display_name`** to be **`String`** and a description **`String to be echoed`**.

Right now we do not support this. Despite that, I think our defaults are already correct. We just need to be able to add something like the following to the bindings.

```python
@plugin_param(key="list_of_strings" display_name="List of Strings",
                          description="A list of strings", item_display_name="String",
                          item_description="String to be echoed")
def do_something(self, list_of_strings):
  for s in list_of_strings:
    print(s)
```

**Comment by TheBurchLog** [comment]
This would add complexity where it wouldn't be utilized.
