### ISSUE TITLE
Pika 0.12 certificate hostname checking

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#140]
When implementing TLS support it seemed like the plugin side worked before I was expecting it to. As in, the cert RabbitMQ was using shouldn't have been trusted by default (since it's using a testing CA) but it worked anyway.

I want to verify that things fail when I think they should fail.

**Comment by hazmat345** [comment]
So this is related to using how we're passing connection information to the plugins.

In Bartender we're using the `TransientPikaClient` from bg-utils to connect to RabbitMQ. This creates the pika connection using an instance of [ConnectionParameters](https://pika.readthedocs.io/en/0.12.0/modules/parameters.html#connectionparameters).

When the plugins connect to Rabbit they're using [URLParameters](https://pika.readthedocs.io/en/0.12.0/modules/parameters.html#urlparameters) instead, since that was the easiest / fastest way to pass the information needed to connect to them.

The default when using URLParameters is to *not* do hostname verification, which explains the behavior I'm seeing.

It's possible to pass SSL configuration options using URLParameters, but it's kind of weird - they essentially become query parameters, and the ssl_options one is expecting a dictionary.

We should just move to using `ConnectionParameters` rather than try and shoehorn the SSL parameters into URLParameters.

**Comment by loganasherjones** [comment]
I agree. We should re use the parameters.
