### ISSUE TITLE
Mongo reverse_delete_rules

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#141]
We currently have two `Reference` fields that don't define a `reverse_delete_rule`, so it defaults to doing nothing. We should be explicit about how we want to handle these deletes.

1. The `system` field in the `Command` model. I'm pretty sure this should be `CASCADE` since it doesn't really make sense to have 'orphan' commands. In fact, I believe that caused an issue for us at some point, so this may help address that.
2. The `parent` field of the `Request` model. I'm not too sure about this one, but I'm leaning towards `DENY` to prevent the ageoff from removing a parent request but leaving the child. If that were to happen now I'm pretty sure any attempt to pull that request out would result in an error when mongoengine tried to dereference the deleted parent.

**Comment by hazmat345** [comment]
Ugg, now I remember why. Trying to add these causes Mongoengine to freak out. This would need to be done on a major version, I think.

**Comment by loganasherjones** [comment]
Also need to consider Instance orphans.

**Comment by hazmat345** [comment]
For the second part of this - the Request model parent field already has a CASCADE rule.
