### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by impredicative** [beer-garden/beer-garden#144]
I would like to request that Python 3.6+ "type annotations" be fully supported for defining parameters.

**Comment by loganasherjones** [comment]
Hi @impredicative. First, thanks for your contribution.

Yes, I am familiar with type annotations. The GIF that you're referencing works (and needs to work) with python versions 2.7 - 3.7. As such, the GIF demonstrates a way that will work with all of these different versions. 

I would love to have support for type annotations. Feel free to contribute back to [brewtils](https://github.com/beer-garden/brewtils) which is the library that would need to be updated.

Here is the issue: https://github.com/beer-garden/brewtils/issues/76

**Comment by hazmat345** [comment]
I'm going to close beer-garden/brewtils#76 since we're consolidating issues into this namespace. Relevant comment is:
 > Now that type annotations are a real thing, it would be nice to have brewtils support them. Whatever functionality we would create needs to be backwards compatible, and ensure that it works correctly with python 2.7 - 3.7.
>
> This alleviates the user from having to specify type in the @parameter definition which is a win.
>
> While we are working on this, we also need to think about how popular libraries like mypy work. Another challenge will be deep inspecting when a type references another class, we will have to discover the parameters for that model as well.

**Comment by scott-taubman** [comment]
Unlikely to tackle this in the current iteration of BG.  Closing for now.
