### ISSUE TITLE
Improper loading of Get-Started Plugin

### ISSUE THREAD

**Issue by NewNork** [beer-garden/beer-garden#1470]
Hey,

I'm trying to do the first steps with beer-garden. Got the local plugin working alright, but the remote plugin as given [here](https://beer-garden.io/docs/plugins/python/remote-guide/) will not be submitted properly.

More specifically the code I'm using in a Docker setup 

```
from brewtils import Plugin, command

class HelloWorldClient(object):
    @command 
    def say_hello(self):
        greeting = "Hello, World!"
        print(greeting)
        return greeting

def main():
    client = HelloWorldClient()

    plugin = Plugin(
        client=client,
        name="hello-world", 
        version="1.0.0",
        description="My First Plugin",
        bg_host="localhost", 
        bg_port="2337",
        ssl_enabled=False,
    )
    plugin.run()

if __name__ == "__main__":
    main()
```

Command line output is

```
2024-03-09 16:20:48,853 - brewtils.plugin - INFO - Plugin docker:hello-world[default]-1.0.0 has started
```

and stuck there. 

http://localhost will see the system and the plugin, but Explore will show no commands. There isn't anything in the beer-garden Docker logs that would point me in the right direction for debugging. I suspect (from playing with setup_logger and receiving errors from there) that something is trying to do an SSL handshake, despite having ```ssl_enabled=False```. 

Happy to investigate further, I just don't know how to dig in.

**Comment by TheBurchLog** [comment]
Hi there!

I will be the first to admit some of our docs are out of date. It has been on my todo list to revisit it.

I just ran the same example and I see the system appear on the interface, but no commands listed, which is strange. I will take a look and see if there is something going on in the background. Thank you for bringing this to our attention.

**Comment by TheBurchLog** [comment]
While I look into it, check out our examples plugin repo:
https://github.com/beer-garden/example-plugins/tree/master

**Comment by TheBurchLog** [comment]
I have to research why, but for some reason a remote plugin is not parsing the client properly when passed into the `Plugin` class `__init__`. For the moment, this is the current work around, you have to assign the client after setting up the Plugin class.

```
def main():

    plugin = Plugin(
        name="hello-world", 
        version="1.0.0",
        description="My First Plugin",
        bg_host="localhost", 
        bg_port="2337",
        ssl_enabled=False,
    )
    plugin.client = HelloWorldClient()
    plugin.run()
```

**Comment by TheBurchLog** [comment]
I think I figured it out. I have a Pull Request with the changes to address it.
https://github.com/beer-garden/brewtils/pull/460

**Comment by TheBurchLog** [comment]
Beer-Garden and Brewtils 3.24.4 have been released. Included in the Brewtils release was the patch for this issue. 

Thank you for the feedback!
