### ISSUE TITLE
Thread-based Scalability

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#15]
If a plugin can be multi-threaded and is local, we should be able to scale that plugin by adding a new thread to a thread pool. This would help with high-processing plugins or plugins that can do things in parallel. This would need to work about the same as docker scalability.

**Comment by hazmat345** [comment]
Closing this as the correct way to handle is by running plugins as containers and letting an orchestration framework decide how to scale.

Also since simply scaling threads is not going to be useful in a lot of cases.
