### ISSUE TITLE
Allow plugin configuration changes from the GUI

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#16]
Local plugin configuration is a pain in the butt because you have to be on the box to configure things. It would be really nice if a plugin could specify a configuration file (YAML/JSON file) and we could allow people to modify it on the box.This would be a big time save as people add new devices to their systems. We will also need to allow them to modify the actual beer.conf file.

If we are supporting docker already, we should allow them to modify the docker stuff as well.

**Comment by scott-taubman** [comment]
This is unlikely to be tackled in the current iteration of BG.  Closing for now.
