### ISSUE TITLE
Old chrome multiple systems

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#165]
Problem with sidebar when there are multiple version of a plugin. Chrome 43.0.2357.

**Comment by hazmat345** [comment]
I'm having trouble replicating this. Can't get it to occur with 43 or 36.

**Comment by loganasherjones** [comment]
Hah, I think the issue was that my browser had cached the previous version of the BG UI and it was affecting the new version. This needs to be addressed by being smarter about our webpack building. #158
