### ISSUE TITLE
Scheduler error counting

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#173]
Currently not updating error count if the scheduler fails to execute a run because of a TLS error.

Also, from #201: If you create a job through the API with an invalid command name the error count does not update.

**Comment by hazmat345** [comment]
May also be related to #201

**Comment by hazmat345** [comment]
Ok, after working on #209 I think I have a clearer picture of what's going on here.

We track the number of successful and failed job runs as part of the mongo `Job` model. Apscheduler does not care or track that for us. We currently update the numbers in the request PATCH handler when the job finishes processing. If the request finished successfully the number of successful job runs is bumped, and if the request raised the number of unsuccessful is bumped.

The problem is that for cases where the job definition itself is invalid we don't get far enough to update the numbers since there isn't a Beergarden Request that completes.

Apscheduler actually has an event system that is pretty easy to hook into. I think we could use this to be more efficient and better organized about how we update the job run numbers.

My issue is this: should there be a distinction between cases where the job request errors (what the error count currently tracks) and cases where the job creation itself fails? They are both "errors" so my initial thought was to just combine them into the current error count, but I can see the argument for having a separate counter.

**Comment by scott-taubman** [comment]
I think we addressed this in #1225, or at least addressed it as much as we're going to for the foreseeable future.
