### ISSUE TITLE
Password Type Fields

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#18]
We should allow people to specify password as a type.

This has a couple of properties:
1. The plain-text password is never stored by BEERGARDEN
2. The plain-text password is never transferred from BEERGARDEN to any of the plugins

I think this means we would need a session secret for plugins, which seems like a good idea anyway. This is an interesting and possibly easy feature to add that would be helpful.

**Comment by scott-taubman** [comment]
This is unlikely to be tackled in the current iteration of BG.  Closing for now.
