### ISSUE TITLE
UI always errors when removing unresponsive plugins

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#182]
We currently wait `plugin_local_timeout_shutdown` seconds for a remote plugin to respond when we remove it. If the plugin is actually down already we'll have to wait that entire time.

Our default backend socket timeout is currently 3000 milliseconds. So trying to remove an unresponsive remote plugin will always generate an error (although the action will still complete successfully).

This will be helped when we combine bartender, but I think we still might want to handle remote plugins differently than local for this case.

**Comment by hazmat345** [comment]
@loganasherjones this will be OBE when we combine Bartender and Brewview, but I think it would be good to have a stopgap 'fix' in the meantime.

What do you think about bumping the default `backend_socket_timeout` to 12ish seconds? That way we  don't have the weird situations where the call to bartender times out, but then the plugin actually gets stopped / removed.

The calls to bartender are all async'd (sp?) so we don't have to worry about tying up the server or anything like that.

**Comment by loganasherjones** [comment]
Yeah, I really can't wait to get rid of bartender. You can bump up the time if you'd like.
