### ISSUE TITLE
Alternate request creation methods

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#184]
Right now the only way to create a request is through the REST api. This is a problem.

We need to structure the app better so that we can easily add new ways to create requests. 

Then we need to add support for creating requests by listening to a message queue.

**Comment by TheBurchLog** [comment]
First candidate for Messaging Queue interface is STOMP. With the way we redesigned the Entry Point structure, this should be easier to integrate. We just have to trust the JMS Topic, and require all objects being sent to be in the `Operation` structure.

**Comment by hazmat345** [comment]
This is now OBE. We have a STOMP entry point and the ability to create requests through it.
