### ISSUE TITLE
Published events TTL

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#185]
Published events should have a configurable TTL with a sensible default.

**Comment by hazmat345** [comment]
I'm no longer convinced this is something we should do. Event consumers can specify the `x-message-ttl` argument when creating their queue, which makes more sense to me than an application-wide TTL on event messages.

I'm not *opposed* to doing this, it's just a very low priority.

**Comment by loganasherjones** [comment]
If this gets done, the TTL should be the same as the corresponding info/action TTL in the configuration.

**Comment by TheBurchLog** [comment]
This has been completed. TTL for messages published to Rabbit align with the Cancel TTL
