### ISSUE TITLE
Brewtils url_prefix spec option

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#186]
There's a mismatch between the brewtils spec and what the brewtils plugin is expecting for the name of the url_prefix.

It's `url_prefix` in the spec but the plugin is expecting a kwarg with the name `bg_url_prefix`.

Should probably standardize on the bg_ since we already have `bg_host` and `bg_port`

**Comment by hazmat345** [comment]
@loganasherjones we should decide what to do here before 3.0 is released.

We have a similar situation with `bg_host` and `bg_port` (host and port). We have deprecation warnings for calling `load_config` with 'host' or 'port' (telling them to switch to using the bg_ versions).

This is significant because the easiest way to create a plugin is to use the `get_connection_info` method:

```python
Plugin(client, name='plug', version='1', **get_connection_info())
```

If you have a BG_URL_PREFIX environment variable the specification will load it correctly, but the Plugin itself will ignore it:

```python
# Plugin wants this:
Plugin(client, bg_host='host', bg_port=2337, bg_url_prefix='/something')

# But get_connection_info is returning this:
Plugin(client, bg_host='host', bg_port=2337, url_prefix='/something')
```

I don't really mind which way we go. It's a little strange because some of the spec names have the bg_ prefix and some don't (#188), so I don't think either way will be wrong, we just need to pick one.

**Comment by loganasherjones** [comment]
I think standardize with `bg_`

**Comment by hazmat345** [comment]
So after working on this I want to narrow the scope of this issue a bit. Since both of these things are published API we can't really yank one of them away without potentially breaking downstream code. So the primary focus of this issue is to make sure that the Plugin with work with either kwarg.

Obviously, having two kwargs that do the same thing is not great. We should move towards removing one, but that will need to go through a deprecation cycle.

**Comment by hazmat345** [comment]
To close the loop on this - the final decision for v3 is to just support both with no deprecation warning.

Moving towards a single name for this parameter should be tracked by #188.

If both names are supplied as kwargs, `bg_url_prefix` will be preferred (and a warning will be logged).
