### ISSUE TITLE
Brewtils spec names

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#188]
We need to think about using the bg prefix for all the brewtils spec names. If a plugin wants to be able to make a connection to somewhere it's natural to want to specify the same things that beergarden needs.

Things like `ca_cert`, `ssl_enabled`, etc. make sense for other things besides beergarden. We shouldn't preclude the use of those name because we're using them.

**Comment by hazmat345** [comment]
Right now we have 

- bg_host
- bg_port
- ca_cert
- ca_verify
- client_cert
- ssl_enabled
- url_prefix
- api_version
- username
- password
- access_token
- refresh_token

I'd propose changing those to:

- bg_host
- bg_port
- bg_ca_cert
- bg_ca_verify
- bg_client_cert
- bg_ssl_enabled
- bg_url_prefix
- bg_api_version
- bg_username
- bg_password
- bg_access_token
- bg_refresh_token

I'd like to add support for the new names in the 3.0 release and deprecate the old names. Unfortunately, solving this issue requires a breaking change. So we'd need to go through a version supporting both.

@loganasherjones any thoughts?

**Comment by loganasherjones** [comment]
I’m kinda indifferent on this one. It might be nice from a consistency stand point. In most cases (like `ca_cert` or `client_cert`) it probably doesn’t make a ton of sense to split the names out. 

I like the consistency, but the only time the prefix actually matters is during CLI parsing. This feels like something yapconf should support better (i.e. if you could set a `cli_prefix` for individual items)

**Comment by hazmat345** [comment]
Yeah, a CLI prefix is probably a better solution.

**Comment by hazmat345** [comment]
Ok, I'm abandoning the vast majority of this issue. I still think it's a good idea, but I think the effort required is too much for too little gain and we need to wrap up v3 changes.

The only parameters I'm still interested in for this are `bg_host`, `bg_port`, and `url_prefix` because there are multiple "names" for those, which is a bad situation.

Here is the current v2 state:
- `load_config` will log a deprecation warning if `host` or `port` is passed as a kwarg.
- `Plugin` only respects `bg_host` and `bg_port`
- `Plugin`accepts both `url_prefix` and `bg_url_prefix`, preferring the latter
- All three `*Client`s accept `bg_host`, `bg_port`, `host`, and `port`, preferring the prefixed versions
- All three `*Client`s are expecting `url_prefix`.

This is what I want to do:
- Keep the deprecation warning if `host` or `port` are ever used. Change the verbiage to indicate that these names will be removed in 4.0.
- Respect both `bg_url_prefix` and `url_prefix`. The "real" (in the spec) name will be `url_prefix`, as that was the more widely-accepted option. However, don't deprecate `bg_url_prefix` because the long-term goal would be to move *everything* to having a `bg_` prefix, and I don't want to deprecate anything that moves *away* from that.

@loganasherjones do you have any thoughts on this? I'm especially torn on the last bullet above - what the "real" name should be. Do you think it matters?

**Comment by hazmat345** [comment]
...and I have to change my mind on that last point.

I added a warning for if *both* kwargs are given (since that's a possibility), and the warning has to say which one is preferred. I'm going to pick `bg_url_prefix` for forward compatibility.
