### ISSUE TITLE
On-Demand Request/Systems

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#19]
When we are able to configure ourselves with Kubernetes and even when we are not, it might be cool to, instead of having a plugin live forever, just have it live "on-demand". This incurs some start-up cost obviously butmeans that we could actually start a plugin at runtime. This is useful if you have a plugin that needs to be started on a particular node in Kubernetes cluster. (Say for example you're operating on a very large file that you don't want to have to transfer between nodes.

**Comment by hazmat345** [comment]
This is very Lamba-like, I'm not sure how well it fits into our model.

**Comment by hazmat345** [comment]
Closing this as it'll be tracked by #22
