### ISSUE TITLE
Out of order events

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#190]
I think we have a weird situation now where due to the timing of when we publish events they could be out of order.

If a request is created with wait=True then the original POST handler doesn't finish until after the request is done. So there's a potential for a race (that I think the PATCH would win) as to which event gets published first.

We could probably 'solve' this by doing an async sleep for some small amount of time in the PATCH after we set the event to release the POST await.

**Comment by hazmat345** [comment]
So this is a real problem. If you watch the events generated by `say_sleep` this is the order:

1. say_sleep created
2. say_sleep started
3. say started
4. say completed
5. say created
6. sleep started
7. sleep completed
8. sleep created
9. say_sleep completed

Both child requests are being created with a blocking `SystemClient`, so this behavior is the result of the POST handler waiting.

This behavior is also messing with the handler timing metrics. The stats for POST requests are going to reflect the entire wait time (but only for blocking=True requests), which I don't think is what we want.

I think the solution for this is to not block in the middle of the handler, we should be blocking at the end.

**Comment by hazmat345** [comment]
Sigh. We can't just wait in `on_finish` because the response has already been written by that point.

**Comment by hazmat345** [comment]
So because of the Brew-view / Bartender interaction we have no way to actually enforce the correct event order here. 

beer-garden/brew-view#105 changes the always-incorrect order to a race condition, which I'm not sure is better.

I think fixing this for real is going to have to wait on #87.

**Comment by TheBurchLog** [comment]
Is this now OBE? I know we have done a lot of overhaul events.
