### ISSUE TITLE
Alternative Database

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#191]
We should explore alternatives to mongo.

**Comment by hazmat345** [comment]
This will actually become feasible after #340 is merged. We'd need to define:

- Layer for the backend (models and db api methods)
- Pruner implementation
- Jobstore implementation

**Comment by scott-taubman** [comment]
This falls under the scope of a full-on re-architecture effort that we hope to do at some point.  I'm going to close this individual ticket as it's not something we're going to work in isolation.
