### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#2]
We need a logo for Beer-Garden

**Comment by gurjarshakti** [comment]
Please Give me Some details and reference for logo.

**Comment by loganasherjones** [comment]
Hey @gurjarshakti Thanks so much for commenting!

Any contributions would be greatly appreciated. We are by no means artists, but I'll try to spell out a couple of the ideas that we had and you can feel free to run in whatever direction it takes you, or come up with your own designs! There were two main graphics we were looking for.

1. A "banner"-type logo that would be the name "BEERGARDEN" in bubble-letters that look like mugs with beer in them, preferably with some foam on the top :smile: :beers: This would be used on our documentation site as well as the README's for a nice bit of flair. 
2. A simple logo that can be used as a favicon to uniquely identify the app. The simpler the logo the better, we've had a suggestion in the past where there was a stem on top of which set a mug. 

Hopefully that gives you some ideas. Please feel free to ask some more questions. And thanks for contributing!

**Comment by ggcarlosr** [comment]
That friend here is my proposal may require some adjustment changes but I would like to know your impressions with respect to the representative icon and text, I hope your comments brother.

![beergarden-logo](https://user-images.githubusercontent.com/37964430/39669494-6405c9c2-50bb-11e8-9b6b-ae42ce5b7966.png)

**Comment by loganasherjones** [comment]
Hey Carlos:

Thanks so much for the contribution! I'm definitely not a graphic designer by any stretch of the imagination and this is way better than what I could do on my own.  I have a couple of thoughts that I'd like to bounce off of you to get your opinion.  

* I'm worried the circle around the stein will be too busy when it is shrunk down into a favicon I think it would be good to just remove the circle, what do you think?

* If we could differentiate the stein color from the leaf color, I think that would help clarify the image a little bit.

* Could we maybe try a more muted green? When I look at the logo now, I think "recycling"

* For the typeface, could we maybe bring the weight down? I'm not sure if that will look good or bad. The "R"s really stand out a lot. I'm undecided if that's a good or a bad thing but am interested in hearing your thoughts on it.

Overall, I really like the concept and hope we can iterate on it and improve it together! Again, I'm not a graphic designer by any stretch of the imagination so I'm open to learning about concepts if I've proposed something that is stupid!

Thanks again!

**Comment by ggcarlosr** [comment]
here the design with the details you suggested, I await your comments

![beergarden-logo](https://user-images.githubusercontent.com/37964430/39734824-df629578-5246-11e8-82a7-f0ca25ef067f.png)

**Comment by loganasherjones** [comment]
@ggcarlosr 🤤 that logo looks amazing! Can you produce the logo itself as an SVG and we can start scaling it?

The font definitely looks better, a couple more notes to collaborate on:

* I think a space between the words beer and garden would be good.
* We kicked it around here a bit, I think the current font reminds me too much of kindergarden or elementary school
* To try to put some more clarity on what we're looking for, we looked on google fonts for about 5 minutes and found this font which we like https://fonts.google.com/specimen/Josefin+Sans  Of course, we are not tied to this font at all, and are interested in your opinion, but thought it served as a basis for research
* Question for you, do you think it would look better all caps? Or should we only capitalize the 'B' and 'G'? I have no clue which would look better, and I'm sure it depends on the font chosen

Thanks so much for all the hard work!

**Comment by ggcarlosr** [comment]
Good day Logan, I think the suggestions are fine .. I will modify what you indicate with regard to the tree...

**Comment by ggcarlosr** [comment]
**# - OPTION 1**
![bg-logo-01](https://user-images.githubusercontent.com/37964430/39767404-b3295f0a-52b4-11e8-9dd9-3b0e9ca6cfdb.png)

**# - OPTION 2**
![bg-logo-02](https://user-images.githubusercontent.com/37964430/39767430-bfe55848-52b4-11e8-8dc9-0aa1684f58a8.png)

**# LINK SVG** 
[SVG OPTION 1](https://drive.google.com/open?id=1IOBPAP6mkavavk_jNUrmz8xrEpDxRGnK)
[SVG OPTION 2](https://drive.google.com/open?id=1EBu0Mn_RelNfD7htN8F-qwl-6L-WhwJU)

**Comment by loganasherjones** [comment]
Oh, I really like option 2! What do you think?

**Comment by hazmat345** [comment]
Oh man, option 2 is super sweet. That is awesome.

**Comment by loganasherjones** [comment]
I also like the slight gap between the mug and tree. Nice touch 👍

**Comment by ggcarlosr** [comment]
excellent the option also I like, I hope also you decide for that one. you need some other type of editable file?

**Comment by ggcarlosr** [comment]
notify me if I make a pull requests so you can add the logo to the project?

**Comment by gurjarshakti** [comment]
Amazing work 🙋👍👍

**Comment by ggcarlosr** [comment]
Perfect where you send attachments of the editable? or create an Pull Request.

**Comment by ggcarlosr** [comment]
That friend already made the extraction request I hope that you merge it to the project. and that the issues may be closed

**Comment by loganasherjones** [comment]
Hey @ggcarlosr, the logos above look great. If I could get one more thing, we could pull this into the project and figure out how to incorporate it into beer-garden.io.

I would like just the icon (i.e. no text) with a transparent background in SVG form. Thanks for all your hard work.

**Comment by ggcarlosr** [comment]
excellent attach several files in different formats which will serve you for different utilities, accept the extraction request that you make please....

**Comment by ggcarlosr** [comment]
How about brother here the editable files that you may need.

[DOWNLOAD HERE](https://drive.google.com/open?id=11ookqQWfBxBWVcFBVKlaYFNRusKgcjER)

**Comment by loganasherjones** [comment]
@ggcarlosr sorry, I was at PyCon and am now back and looking at this. Thanks very much for your contribution. I will be sure to put you in our documentation. I plan on using the logo the next time I get around to updating the site!

**Comment by ggcarlosr** [comment]
thank you for your answer friend, I hope you accept the extraction request and that this issue can be closed when you can.

**Comment by loganasherjones** [comment]
Thanks so much to @ggcarlosr for the new logo! Hope we can work it into the application soon, for now it is in the documentation!

**Comment by loganasherjones** [comment]
By the way, I'm open to suggestions on things we should do differently from a design perspective on the documentation website (https://beer-garden.io/) let me know if you like the incorporation of the new logo!
