### ISSUE TITLE
Scheduler job interval based on prior run completion

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#209]
If I have a job that takes between one and two minutes to run it would be very helpful to be able to schedule a job to run 5 minutes after the completion of the current run. Right now it's only possible to say 'run this job every 5 minutes.'

**Comment by hazmat345** [comment]
@loganasherjones how difficult do you think this would be?

**Comment by hazmat345** [comment]
So I think this is going to be pretty difficult to do correctly. The underlying problem is that the triggers have no concept of state, so the `IntervalTimer` is essentially a time delta.

When the scheduler submits a job to the executor it immediately calculates `next_run_time` for the job. There doesn't seem to be any way to postpone this calculation until that execution completes.

The best I can come up with is something like this:
https://github.com/beer-garden/brew-view/commit/a7f06f083e6622c556118a2adbae6789ad207bf8

Basically, the executor now waits for the request to complete. Once it does it reschedules the job, which recalculates the `next_run_time`.

Some potential issues:

- Now that the executor isn't fire-and-forget we have the potential to run out of threads. Will be mitigated when we move to Python 3.6 and can use native coroutines.
- The next run time in the database (and shown in the UI) is going to be incorrect for the period of time between job start and job conclusion.

@loganasherjones any thoughts? Someone is interested in this.

**Comment by loganasherjones** [comment]
APScheduler doesn’t have a way to do this natively. In theory this can already be supported through request webhooks. We could create a job with a date trigger every time the request finishes. I think there are other ways too, but I’ll need to think of a better solution.

**Comment by loganasherjones** [comment]
Something like the following should work:

1. Create a new Trigger within APScheduler, let's call it `DelayedIntervalTrigger`
2. The `DelayedIntervalTrigger` is a special type of `DateTrigger` which doesn't get deleted after it has been fired the first time.
3. When a job whose trigger is `DelayedIntervalTrigger` gets fired, we set, in the metadata of the request `trigger_interval`
4. In the `PATCH` handler of the request (although this would really be better as an event listener or something) we check to see if `_bg_job_id` is still a valid job and if `trigger_interval` is set, then we update the trigger time. 

Thoughts?

**Comment by hazmat345** [comment]
I think the new trigger type is good - we need some way to distinguish this from a 'normal' interval.

I'm pretty opposed to putting that logic in the PATCH handler. I think it'd be OK in a listener I guess, but it seems like that would be adding another moving part.

Would there be any benefit to doing it that way over just doing it in the scheduler executor? It seems like what I originally proposed is pretty similar to what you're proposing. Then we don't have to worry about the request metadata, we can just get the Job directly (and the Trigger) from the job ID. That way we can reuse the mechanism that already exists and we don't have to put stuff in the handlers.

**Comment by hazmat345** [comment]
So I'm less opposed to doing stuff in the handler... that's basically how we handle waiting for the request to complete when it's created.

**Comment by hazmat345** [comment]
FYI - changes for this also give us the ability to specify a max number of concurrent job executions.
