### ISSUE TITLE
Docker-based plugin registration

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#21]
Ideally you should be able to register your plugin as a docker container. For example, if you register a plugin with a particular docker-registry/container name/command. BEERGARDEN should be able to run that docker container as a plugin. This would help should we ever get into the business of scalability with plugin management.

**Comment by hazmat345** [comment]
@loganasherjones Is this still a good idea? This seems pretty similar to what you'd get from using Kubernetes or something to run your plugin containers.

**Comment by loganasherjones** [comment]
Yeah I don't see any reason to leave this open. This is far away and we can reassess when the time comes.
