### ISSUE TITLE
Rpm install not clearing old package metadata

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#215]
When upgrading via the rpm it looks like the beer-garden packages aren't getting fully removed.

When upgrading from an older version I can see some extra directories in the `lib/python3.6/site-packages` directory:

- brewtils-2.4.1-py3.6.egg-info
- brewtils-2.4.4.dist-info
- brew_view-2.4.4-py3.6.egg-info
- brew_view-2.4.7.dist-info

It's also happening with non-beergarden packages:
- six-1.11.0.dist-info
- six-1.12.0.dist-info

The old directories are all empty, so this may not actually be a problem.

**Comment by hazmat345** [comment]
This is actually a problem.

To see it in action:
- Use the rpm to install a beer-garden that uses a brewtils version that's less than 2.4.3 (say beer-garden 2.4.0).
- Start beer-garden
- Then upgrade (again using the rpm) to the latest version of beer-garden (2.4.5 as of right now).

The upgrade will succeed, but there will be some errors about not being able to import methods from `brewtils.log`.

In brewtils 2.4.3 we changed the `brewtils.log` package to a module. Running beer-garden caused a directory to be created at `brewtils/log/__pycache__`, and this directory does not get deleted when the rpm is upgraded. This is causing the import machinery to look in the wrong place.

**Comment by hazmat345** [comment]
Man, this is pretty involved. Because of how rpm gets updated fixing this is non-trival. Basically, on an upgrade we want to completely remove /opt/beer-garden/lib and then install the new files (how it would work if you run yum erase and then install the new version).

Unfortunately, when upgrading the new package is installed *before* the old one is removed. So there's no appropriate time to hook in and remove that directory. Removing it in the before_install results in an error for every file in the original package since it's no longer there when rpm wants to remove it.

**Comment by hazmat345** [comment]
Make some progress on this. Last thing to do is fix where in the process the config migration happens. I believe it needs to go in `after_remove.sh` so it gets executed after the extra directories have been removed.

**Comment by hazmat345** [comment]
@loganasherjones for the upgrade case, do you think we should be generating logging configs if they don't exist?

**Comment by loganasherjones** [comment]
Yeah, I think we should generate logging configs if they don't exist.

**Comment by hazmat345** [comment]
Hmm, do we do the same for the regular configs? I think yes?

If the rpm is installed, the config files are removed, and then you upgrade, we'd want new configs generated, right?

**Comment by hazmat345** [comment]
Also, the upgrade currently errors if the init script is missing (since it can't stop the service). We should probably be better about handling that.
