### ISSUE TITLE
"Extra" parameter definition

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#216]
While looking into a dynamic choices issue I saw that one of the commands looks like this:

```python

@parameter(
    key="index", type="String", choices=STATIC_CHOICES, default="a", is_kwarg=True
)
@parameter(
    key="message",
    type="String",
    description="Say what we want",
    optional=False,
    choices={
        "type": "url",
        "display": "select",
        "strict": True,
        "value": CHOICES_URL,
    },
)
def say_specific_from_url_with_parameter(self, message):
    return message
```

The problem here is the `index` keyword. It's defined as being a kwarg, but the method has no corresponding `**kwargs` parameter.

We'd expect this to fail when the request is processed, and it does (with "say_specific_from_url_with_parameter() got an unexpected keyword argument 'index').

This seems like something that we could catch at decorator time.

**Comment by loganasherjones** [comment]
Agreed, this seems like a bug for brewtils.
