### ISSUE TITLE
Easy Client Cleanup

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#223]
While converting some `EasyClient` methods I noticed some things that could be improved but that would be API changes:

- `get_instance_status` returns the actual instance, not the instance status
- The `default_exc` for `get_logging_config` is `RestConnectionError`. It should probably be `FetchError` to match other GET requests.
- `get_queues` `default_exc` is undefined, so it defaults to `RestError`. It should probably be `FetchError` to match other GET requests.
- `clear_queue` and `clear_all_queues` `default_exc` is undefined, so it defaults to `RestError`. It should probably be `DeleteError`
- `pause_job` and `resume_job` don't return anything. They should probably return ~True~ the updated job on success to match other methods.
- `get_version` should probably return response.json(), not the response object

**Comment by hazmat345** [comment]
@loganasherjones how do you feel about these? The only one I'm really concerned about is the first one - I'd like to fix that ASAP but I'm worried that people could be depending on the current behavior.

Probably the right thing to do is create a `get_instance` method, throw a warning in the current `get_instance_status` that the behavior will be corrected in 3.0, and then do that.

**Comment by loganasherjones** [comment]
I'm on board with all the changes!

**Comment by hazmat345** [comment]
Ok. I'm going to open a new issue for adding the `get_instance` status and throwing up some sort of warning from `get_instance_status` that the behavior will change in 3.0.
