### ISSUE TITLE
Plugin Debug Mode

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#227]
It would be neat to allow plugins to run in some sort of debug mode:

```python
x = Plugin(client, name="foo", debug=True)
```

That would let us do neat things. The first thing could be to also send the stacktraces when a request processing method raises an exception.

We probably don't want to put the stacktrace in the output since we don't want to change 'real' behavior based on this flag. Should probably throw it in the metadata or something.

**Comment by loganasherjones** [comment]
We have #287 this issue does not specify any other use case well enough to keep it open.
