### ISSUE TITLE
Action Triggers

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#24]
Triggers are going to become important for BEERGARDEN. This is a major feature and will probably be broken down into other features. I would like to be able to trigger off of any event in BEERGARDEN. There are two types of trigger registration we need to consider (possibly more):

1. I would like to register a trigger when my system is registering.
2. I would like to register a custom trigger in the GUI

In example 1, this would assume you've made some custom plugins, and you want these plugins to automatically kick off jobs when something else is done. This can be done on plugin registration time to allow for better hot deploy capabilities in BEERGARDEN. i.e. you don't have to manually go to the GUI to create a flow/trigger/whatever we are going to call them.

In example 2, the plugin developer might not have a clue what type of trigger you want, and they may be so different that it doesn't make sense to include in the plugin registration. Take for example, a REST plugin. It doesn't make sense to include a trigger inside a REST plugin because that plugin is not specific enough. Still though, if your REST plugin only does one thing in your setup then you may want to trigger on that.

## Trigger Registration ##
Triggers need to be able to register on **anything** that happens in BEERGARDEN. If you want to register on the **`/api/v1/systems`** endpoint, you should be able to, same (obviously) for **`/api/v1/requests`**

This means we'll have to come up with a simple way to support triggers such that if we add a new field to the **`Request`** model, we don't have to worry about chaining trigger code as well.

**Comment by TheBurchLog** [comment]
@hazmat345 Let's chat about that plugin you saw.

**Comment by hazmat345** [comment]
We have a plugin that provides some of these features already. This issue would track incorporating that into Beergarden proper.

**Comment by hazmat345** [comment]
From #31, this should support the following:

> I have a command and it needs to be executed a the end of another command.
