### ISSUE TITLE
"Expected" exception logging

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#243]
Exceptions arising in brew-view are pretty ugly in the logs. It would be cool to make them nicer.

For example, for things like a TimeoutExceededError it doesn't make sense to log the stacktrace - it's a 'normal' exception that gets translated to an appropriate response code. For things like that the stacktrace is just noise.

Probably need to have our `BaseHandler` override `tornado.web.RequestHandler.log_exception`.

**Comment by scott-taubman** [comment]
#1146 is essentially a duplicate of this, but since that issue is a little more descriptive I'm going to close this one.
