### ISSUE TITLE
Mongo Pruner Child Requests

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#244]
I think we should limit the mongo pruner behavior to only removing parent requests.

We encountered an issue where an `action` request used a problematic `info` request. The `info` TTL was set much shorter than the `action` TTL, which made troubleshooting difficult.

I think we might need to be smarter about nested requests in general. I think it might be possible to have the pruner remove a parent but leave the child, which would be pretty bad.

**Comment by hazmat345** [comment]
@loganasherjones do you have any thoughts on this?

**Comment by loganasherjones** [comment]
Yeah, I'm fine with limiting the `action`/`info` TTL to only applying to parent requests and not child requests.

We should *never* have the age off job delete a parent without also deleting all children. This shouldn't be allowed as a matter of database integrity.
