### ISSUE TITLE
Request Groups

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#251]
This is pretty nebulous, but I wanted to jot it down.

It could be useful to group requests by some sort of group id. If I had some python script that wasn't a Beergarden plugin that created multiple requests as part of one task it might be nice to be able to group them together.

This would be different from a parent/child relationship, it would be more sibling-like.

**Comment by loganasherjones** [comment]
I think you can do this by using `metadata` on a `Request`.
