### ISSUE TITLE
Event Listener

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#253]
We need a capability that will listen to beergarden events and update the database accordingly.

**Comment by TheBurchLog** [comment]
Expanding this ticket to build a generic Event Manager/Listener. Where we can have multiple event types that we can trigger different actions off of.

Example:
When system starts up, mirror event to Parent to infom that downstream systems are available.

**Comment by TheBurchLog** [comment]
@hazmat345 I am pretty sure this is done and checked into V3. Can we close this ticket?
