### ISSUE TITLE
Command Groups

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#256]
Consider a plugin that is trying to mock out the docker command.

In this plugin, we want to create separate classes that represent different sub commands. So if I have the command network and the sub-command create on the system docker I need to be able to represent these in BEERGARDEN. In order to stay modular, I'd like to maintain these commands as separate classes.

Basically, I want to decorate a class like the following and have it make sense in BEERGARDEN

```python
@system(name="docker")
class Docker(object):
  # Some implementation stuff for docker

@command_group(parent="docker", name="network")
class Network(object):

  @command(name="create")
  def create(self, arg1, arg2):
    # do create network

  @command(name="delete")
  def delete(self, arg1, arge):
    # do delete network
```

Some things to consider include,
* How does this affect the request API?
* How can we infinitely nest things?
* How do we call the nested class from the plugin in brewtils?
* How does this look in the GUI?
* Do we support non-standard init of objects?

**Comment by hazmat345** [comment]
We can already almost support this with metadata. Currently commands don't have a metadata field, but there's no reason they can't have one. Then we could do something like this:

```python
@command(group="foo")
def my_command():
    pass
```

And do some fancy UI magic to group those things together.

**Comment by hazmat345** [comment]
This is part of #358

**Comment by hazmat345** [comment]
We could also group Systems as well.

**Comment by TheBurchLog** [comment]
Commands now have grouping/tagging in 3.22.0
