### ISSUE TITLE
Inspect docstrings for plugins

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#257]
To make plugin developers lives easier, it would be cool if the BEERGARDEN bindings looked at the doc strings provided on a class/method to determine some information about the plugins. In particular for python, it is possible to determine parameter type, and description from the docstring itself.

We wold probably implement this using a sphinx or pydoc parser. If we go with sphinx, it will increase the overhead of installing the `brewtils` package which can be a little annoying.

**Comment by hazmat345** [comment]
@loganasherjones 

So after thinking about this it kind of violates the zen of python - there should be one way to do things. I don't think it would really be worth the upkeep to provide a completely separate way to specify parameter values like this.

**Comment by loganasherjones** [comment]
Yeah, really the only thing we would be grabbing out of the docstrings at this point would be the description.
