### ISSUE TITLE
Plugin Authorization

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#259]
As a plugin developer, I want to be able to control authorization to my plugin and it's commands. Specifically I want to be able to control the fidelity at which my plugins can be discovered as well as command and controlled. In addition I may want the fidelity at the command level as well.

For example, lets say I have the plugin foo with commands **`bar`** and **`baz`**. **`baz`** is an administrative function and I do not want many people to be able to do it. I should be able to (hooking in through authentication) specify which users are allowed to access **`baz`** without affection **`bar`**. In addition, if foo should only be available to some users, I should be able to specify that as well.

This will greatly depend on the type of authentication used.

**Comment by scott-taubman** [comment]
Auth as it is currently being implemented is not intending to allow the plugin developer to control access to the plugin.  This is instead managed by a garden administrator.  I'm going to close this for now as it's not something we're likely to pursue in the foreseeable future.
