### ISSUE TITLE
Transactions / rollback procedures

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#260]
It would be nice to have a way to indicate some sort of rollback procedure to be called if an exception is raised during processing. It would also be nice to have some sort of transaction for nested requests so that all the rollbacks could be invoked in the event of an exception.

**Comment by hazmat345** [comment]
Hi @loganasherjones 

So I can't every really imagine a case where this would be better handled in the framework vs just being handled as part of the normal plugin logic. Is this something that we could realistically provide?

**Comment by loganasherjones** [comment]
> Is this something that we could realistically provide?

Yes we could provide this. I'm imagining something like this:

```
client = SystemClient(...)
client.do_thing(_rollback="undo_thing")
```

We would use the same lexing/parsing we do for the choices.

That being said, no one is asking for this. So I'm just going to close it.
