### ISSUE TITLE
Custom parameter validators

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#262]
It may be possible that someone would like to do complicated parameter validation by using another `command` of the plugin. We already do something very similar for dynamic choices.

Note that a big potential drawback of this would be that the frontend would have no way to know about this, so validation failures would only occur on the backend. We could potentially rerun the validation each time the value changes, but that could get expensive.

Consider the following example:

```python
class MyClass(object):
  @parameter(key="x", type="int")
  def do_something(self, x):
    if x % 3 != 0:
        raise InvalidParameter("No good")
    self.process_x(x)
```

It would be neat if instead you could do something like this:

```python
class MyClass(object):
  @command
  def super_validate(self, x):
     return x % 3 == 0

  @parameter(key="x", validate="super_validate()")
  def do_something(self, x):
    self.process_x(x)
```

**Comment by hazmat345** [comment]
Going to close this as wontfix. Nobody is asking for it, it's complicated, and it opens a can of worms. Maybe one day!
