### ISSUE TITLE
Lifecycle hooks for plugins

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#263]
It would be nice to be able to hook into the plugin initialization (and shutdown) process.

**Comment by hazmat345** [comment]
So off the cuff, something like this where we don't pass an instance directly, but we provide hook stubs that can be overridden:

```python
plugin(
    classObject=my.class.definition,
    configFunc=myConfig(),
)
```

**Comment by hazmat345** [comment]
But after thinking some more, I'm not really sure this would be net benefit. Closing and we can reopen if we can think of a concrete usecase.
