### ISSUE TITLE
Add init args to Class/System

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#264]
Right now, BEERGARDEN assumes that the class passed to it will be an already instantiated class.

While this is fine, it may also be acceptable to pass in a class that has arguments on it as the following:

```python
@BGSystem
class Calculator(object):

  def __init__(self, offset=1):
    self.offset = offset

  @register
  def add(self, x, y):
    return x + y + self.offset
```

and then in a plugin_start

```python
my_plugin = Plugin(class=Calculator)
my_plugin.start()
```

In this case we know that the offset is 1, but if there are no defaults provided, what we can do is modify the command and say these are required parameters for the command itself.

So in this case we would add the offset to the parameters for command add, but we would also know a default.

**Comment by loganasherjones** [comment]
I don't have a good use case for this. Closing.
