### ISSUE TITLE
Persist request updates from remote plugins

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#265]
Consider the following; a remote plugin takes X seconds to process a request. In those X seconds, BEERGARDEN is down or cannot be reached when the plugin is finished. How does the plugin notify BEERGARDEN about the new status/output of the request?

This indicates we need a better communication method for plugins. In my mind, there are two main solutions to this problem:

1. create a protocol for 2-way communication over the message queue
 * The plugin response queue would have to be persistent
2. Create a local-proxy which the plugin talks to when it is done processing message.
 * This proxy would be responsible for ensuring the delivery of the request updates to BEERGARDEN

Option 1 requires a major(ish) change to the way plugins communicate holistically with BEERGARDEN. Option 2 requires a little bit more work for the bindings, but doesn't require a change to the way plugins communicate.

**Comment by loganasherjones** [comment]
We already have retry logic that solves this problem well enough. #255 describes changing some of the communication strategies for plugins themselves.
