### ISSUE TITLE
Configurable message queues

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#266]
Right now, BEERGARDEN takes an opinionated view on how the queue it uses to communicate with a plugin should be configured. Namely, it determines things like, max-priority, durability, persistence, etc. I'm not quite convinced this is the right behavior. It is possible for a plugin to want a different level of durability or persistence etc.

We should enable this behavior. Something like the following could work.

```python
from brewtils.plugin import RemotePlugin

my_object = MyClass()
my_plugin = RemotePlugin(my_object, queue_args={"max_priority": 1, "persistence": true})
```

**Comment by hazmat345** [comment]
From #53 the queue max size should be part of this.

**Comment by scott-taubman** [comment]
This is unlikely to be tackled in the current iteration of BG.  Closing for now.
