### ISSUE TITLE
System / Command Domain Specific Language

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#27]
It would be very useful to define some sort of language for referring to specific system/version/command/parameters. This may be useful in areas such as getting a SystemClient.

For dynamic choices we need some way to specify that another parameter on the current command should be used as an input for a choices-retrieving command. We want to use the **`index`** parameter to **say_specific_with_choices_argument** as the **key** parameter to the **`get_choices_with_argument`** command, and we want to use the result as the choices for the **message** parameter.

```python
@parameter(key='key', type='String', choices=['x', 'y', 'z'])
@command(command_type="INFO', output_type="JSON")
def get_choices_with_argument(self, key):
  return {
    'x': ['a', 'b', 'c'],
    'y': ['d', 'e', 'f'],
    'z': ['g', 'h', 'i']
  }[key]

@parameter(key="index", type="String", choices=['x', 'y', 'z'], default = 'x', is_kwarg=True)
@parameter(key="message", type="string", description="Say what we want", optional=False,
  choices={'type': 'command', 'display': 'select', 'strict': True, 'parameter_map': {'index': 'key'},
    'value': {'command': 'get_choices_with_argument', 'system': 'dynamic', 'version': '1.0.0.dev'}})
def say_specific_with_choices_argument(self,message,**_):
  return message
```

The **parameter_map** is pretty clunky. It would be nice to be able to say something like **`'command': 'get_choices_with_argument(key=index)'`**.
Some issues:
* Shouldn't the system and version (and maybe instance) be incorporated into the Command then? So something like **`'dynamic[1.0.0.dev][default].get_choices_with_argument(key=index)'`**? (We can always default ot current values so it doesn't HAVE to be so verbose)
* We should have the ability to specify version ranges, probably something like how npm handles version ranges.

**Comment by aamccaslin** [comment]
We also need to be able to have parameter values be conditional on another parameter in an easy way. Something like:

```python
@parameter(key="switch", type="Boolean", is_kwarg=True)
@parameter(key="message", type="String", description="Say what we want", optional="$switch")
def say_specific_conditional_parameter(self, message, **_):
  return message
```

**Comment by hazmat345** [comment]
All aspects of this are either done or covered by other issues.

Version range: #20
Query other system: #272 
Dynamic optionality: #415
