### ISSUE TITLE
Remote Plugin Runner

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#271]
The LocalPlugins are considered "managed" plugins. (i.e. if the process dies they get restarted and STDOUT gets redirected to the logger). There is really no reason this can't be the same way for the Remote Plugins. We should do that.

**Comment by hazmat345** [comment]
Going to close this as wontfix. The local plugin process management is a *huge* source of complexity that I don't think we should be introducing to remote plugins. Instead, we should be adding things that make it clear when a user is about to do something unrecoverable (like stopping a remote plugin). We should also provide the ability to pause remote plugin message processing.
