### ISSUE TITLE
Create a systemproxy object

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#273]
When mirroring a client, it is often the case that I want to basically just pass through to the actual client and am basically creating the beer-garden client class because I have to. If we had #6 done, then this behavior would probably be OBE, but since creating our own docstring parser is somewhat difficult and there isn't a guarantee that we can infer everything correctly, this still seems like it might be a decent  solution when our docstring parser inevitably gets something wrong. Here is what I'm envisioning. Let's say I have the following client implementation (that I cannot decorate because I don't own the code):

```python
class ThirdPartyLibrary(object):

    def __init__(self, somevar):
        self.somevar = somevar

    def foo(self):
        """Return the string 'something'"""
        return "something"

    def bar(self, x, y):
        """Add x and y together and return"""
        return x + y

    def dont_expose_me(self):
        """Does some wonky internal stuff.
           This should probably be a private method but its not. Get over it."""
        pass
```

I want to convert this code into a beer-garden plugin. Right now, I would have to create a separate class, pass in the `ThirdPartyLibrary` instance and then just proxy all the calls. The client code ends up looking something like this (yes you could use inheritance, but it only saves you from re-typing the description) :

```python
class BGThirdPartyLibraryProxy(object):
    
    def __init__(self, proxy):
        self._proxy = proxy
        
    @command
    def foo(self):
        """Return the string 'something'"""
        return self._proxy.foo()
    
    @command
    @parameter(key='x', type='Integer')
    @parameter(key='y', type='Integer')
    def bar(self, x, y):
        """Add x and y together and return"""
        return self._proxy.bar(x, y)
```

This is a common form and we could at least provide something like the following:

```python
from brewtils.proxy import Proxy
lib = ThirdPartyLibrary(somevar='somevar')
parameter_info = {'default': {'x': {'key': 'x', 'type': 'Integer'}}, 'bar': {'y': {'key': 'y', 'type': 'Integer'}}}
proxy = Proxy(lib, 
              proxy_dest='_proxy', 
              parameter_info=parameter_info,
              excludes=['dont_expose_me'])
plugin = RemotePlugin(proxy, **connection_args)
```

**Comment by hazmat345** [comment]
This is a pretty interesting thing... I especially like the idea of a set of overall parameter definitions. Those can then be combined with a client instance.

Taken to the logical conclusion, this could enable creating clients with no annotations (#915)

**Comment by scott-taubman** [comment]
This is unlikely to be tackled in the current iteration of BG.  Closing for now.
