### ISSUE TITLE
Better DateTime support

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#275]
EDITED:

The formatting issue in this description is the smallest part of this issue. See the comments.

----

I may want to format my Date Time parameter as follows:

```python
@parameter(key='x', type='DateTime', format="%A, %d. %B %Y %I:%M%p")
def command(self, x):
    pass
```

**Comment by loganasherjones** [comment]
We don't really have good support for datetimes at all. Right now a datetime is just handled as an integer in all cases except the UI. So to actually get a datetime you would do:

```python
from datetime import datetime as dt

@parameter(key='x', type='DateTime', format="%A, %d. %B %Y %I:%M%p")
def command(self, x):
    x = dt.utcfromtimestamp(x)
```

**Comment by hazmat345** [comment]
I'm not sure I understand the goal of this - is the idea that if you say a parameter is a `DateTime` we'd give you an actual `DateTime` object instead of the epoch time?

How would we handle which timezone to use? I guess we could just always use UTC, but that seems not great?

**Comment by loganasherjones** [comment]
Yes, we would want to give `datetime` objects back here. I agree this is low priority since no one is asking for it.

P.S. The format string would just give us a hint on how to parse the incoming input time. (i.e. if someone want to send us a datetime in ISO format, we would just parse ISO formatted time out of a string)
