### ISSUE TITLE
Default parameter types

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#276]
It would be cool if there were a way to change the default parameter types. Something on the `system` or `command` decorators would be neat:

```python
@system(default_param_type='String')
class MyThing(object):

    @parameter(key='x') # 'x' should be a string type
    def my_command(self, x):
        pass
```

**Comment by loganasherjones** [comment]
Not enough value to warrant. If there is community interest, feel free to add to this post
