### ISSUE TITLE
load_config / get_connection_info autouse cli args

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#278]
Can we assume that a plugin author using these methods wants to use CLI args as sources, similar to how we currently assume they want to use environment variables?

This is mostly because I got pretty tired of always passing `cli_args=sys.argv[1:]` all over the place.

**Comment by loganasherjones** [comment]
There is not a clear precedent order. Also, there doesn't seem to be a good way to decide on what CLI args are valid to look at.
