### ISSUE TITLE
Better SystemClient resolved information

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#279]
If I generate a systemclient with a name, version and instance name I can't figure out what I just resolved.

```python
def foo():
  instance_name = 'foo'
  system_name ='bar'
  system_version = '0.0.1'
  return SystemClient(**args)

def bar():
  client = foo()
  # How do I figure out system name/version instance name?
  # given just the client.
```

**Comment by TheBurchLog** [comment]
#76 consolidate these tickets

**Comment by SpecificallyGravity** [comment]
@TheBurchLog @hazmat345 Is something like the following OK?
```
    class SystemClient(object):
        def __init__(self, ...):
            self.client_info = {'system_name': <name>, ....}
```
Draft solution in `issue/279` branch.

**Comment by hazmat345** [comment]
I think what's in the branch is interesting, but kind of dangerous. It kind of breaks what little bit of encapsulation Python provides (the leading underscore) by default, unless I remember to add any new attribute to the "ignore" list when I add it.

I also think it's kind of overkill - there are really only a few attributes that we want to expose, and I'd rather expose the minimum amount of stuff that's necessary.

We really need to make it easy for someone with a `SystemClient` instance to determine these specific things:
- system name
- system version
- system namespace
- default instance name

So this is really all we need to do, 

```python
@property
def bg_resolved_system(self):
    return self._system

@property
def bg_default_instance(self):
    return self._default_instance
```
