### ISSUE TITLE
Consolidated Configuration File

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#28]
We need to consolidate the multiple configuration files - there's a large amount of overlap (settings needed by both bartender and brew-view) and often it's not intuitive where a config setting belongs (event_persist_mongo needs to be in brew-view, but event_mongo_ttl needs to be in batender).

**Comment by hazmat345** [comment]
Since the plan is to merge brew-view and bartender this will roll into that effort.

**Comment by hazmat345** [comment]
This is OBE now that v3 is done!
