### ISSUE TITLE
Add Support for file-type parameters

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#288]
I want to be able to do the following:

```python
class Foo(object):

    @parameter(key="csv_file", type="file")
    def read_csv(self, csv_file):
        csv.reader(csv_file)
```

We should support file types natively.  This requires quite a bit of work:

1. We need a new API for uploading files
2. Ideally we would support multiple file drivers (at least s3 and native) but only native for now
3. Native storage will be based off of MongoDB GridFS
4. Plugins will download the files automatically based off of the driver specified
5. Parameters in the request will be replaced with a dictionary which include the URL for the file as well as a type specification
6. We will need plugin temp directories for handling these files.
7. Files will automatically be cleaned up from the temp directories
8. The UI will need to be updated to use the new file upload API

**Comment by TheBurchLog** [comment]
Is this the ticket that @SpecificallyGravity is working off of?

**Comment by SpecificallyGravity** [comment]
Working off of #368

**Comment by TheBurchLog** [comment]
This would require us to add Drivers to the input parameters. We need to determine which storage mechanisms we would want to utilize before starting any work on this.

**Comment by hazmat345** [comment]
It would be really cool if additional drivers were installable as standalone things.

**Comment by scott-taubman** [comment]
This is done to the capacity that we're going to do it in the current iteration of BG.  Closing.
