### ISSUE TITLE
Move type-specific information to Parameter

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#289]
Right now, things like `max` and `min` are stored on the parameter object itself. The behavior of each of these fields changes based on what the type is. To prevent the Parameter model from becoming too large while I was adding the file parameters, I added the `type_info` section to the parameter.

This means that our parameter initialization definition will not grow indefinitely as we add new features specific to individual types.

**Comment by hazmat345** [comment]
If we go this route it's going to create a hard break between beergarden and brewtils versions that work together. Perhaps put the `min` and `max` info in `type_info` in addition to where it already is for a couple of application versions.
