### ISSUE TITLE
Blue / Green markings for Systems

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#29]
It would be really cool to have the ability to do blue / green deployments for systems. We can already have multiple versions of the same system deployed, but we're limited in how we route requests to them. We would need the ability to be more dynamic with that.

**Comment by TheBurchLog** [comment]
Not sure what blue/green deployments would look like. Going forward, we are looking at the ability the restrict access to systems based on their Namespace. With that future requirement in mind, I think this is no longer required.
