### ISSUE TITLE
File Upload Limit

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#292]
By default, tornado has an upload limit of 100MB.

If we want to increase this, there is technically a setting for it. But since tornado has to load everything into memory by default, the better solution for this is putting nginx in front of our server and allowing nginx to handle file uploads.

**Comment by TheBurchLog** [comment]
Solution has been posted by the tornado developer here:
https://github.com/tornadoweb/tornado/issues/2952

Solution
use @stream_request_body: https://www.tornadoweb.org/en/stable/web.html#tornado.web.stream_request_body

**Comment by TheBurchLog** [comment]
Technically base64 gets around this for us for file uploads. So we just need to promote that to get around the tornado max size issues.
