### ISSUE TITLE
Update scheduled jobs

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#294]
It'd be good if we could update a job (specifically, change the system version).

**Comment by TheBurchLog** [comment]
@SpecificallyGravity Can you take a look at how hard it would to reload a Job with new parameters.

**Comment by SpecificallyGravity** [comment]
Looks like APscheduler has the following functions that support this:

> - [reschedule_job](https://apscheduler.readthedocs.io/en/stable/modules/schedulers/base.html#apscheduler.schedulers.base.BaseScheduler.reschedule_job)

> - [modify_job](https://apscheduler.readthedocs.io/en/stable/modules/schedulers/base.html#apscheduler.schedulers.base.BaseScheduler.modify_job)

Watchdog is much less sophisticated, but it also doesn't care about anything except for the `trigger`-related information.  If that changes, it may be easier to remove the old job and replace it.

**Comment by hazmat345** [comment]
There's some interest in getting this done.

**Comment by TheBurchLog** [comment]
This should be easy to do if you use the ID field and set that to the Job ID generated by Mongo. Then set `replace_existing=True`. This should overwrite the current trigger with the new one.

https://apscheduler.readthedocs.io/en/stable/modules/schedulers/base.html?highlight=replace_existing#apscheduler.schedulers.base.BaseScheduler.add_job
