### ISSUE TITLE
How will we visualize in the nav bar when we have too many systems

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#3]
When we have 20+ systems we have no way to scroll down the list, how will we deal with that? Right now the more we have the further the screen expands. So now the application is more than 100% height.

**Comment by aamccaslin** [comment]
Moved to https://github.com/beer-garden/brew-view/issues/2

**Comment by hazmat345** [comment]
Closing as wonfix, will be addressed by UI redesign.
