### ISSUE TITLE
Auto-refresh choices

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#32]
For choices which are semi-dynamic (that is, they have the potential to change but change relatively infrequently), it would be nice to be able to specify that beer-garden should auto-refresh these choices.

This might be much easier once we have #10 done. Consider the following scenario where we have a plugin that can `discover_services`. These services do not change often, but when it does change, you don't want to have to restart the plugin to get these new changes. So we have a method `discover_services` which can be used as a source for a choice. We want to refresh it once every 15 minutes.

```python
@command
def discover_services(self):
    # Do something to discover services
    #return services

@parameter(key='services', 
           choices={'type': 'command', 'value': 'get_choices', 'refresh': 900})
def my_method(self, services):
    # Do something with services
```

**Comment by hazmat345** [comment]
In order to support this we'd need to implement some sort of request caching, and I don't believe that's something we're really interested in pursuing.
