### ISSUE TITLE
Easy Plugin Event Listeners

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#327]
It would be super cool if we made it easy for a plugin to tie into Beergarden events. Something like this:

```python
@system
class TheClient(object):
    @on_event(events.BREWVIEW_STARTED)
    def handler(self):
        print("Hello, Brew view!")
````

**Comment by TheBurchLog** [comment]
Marking this OBE. In the 3.22.0 we released the ability to trigger off system status changes. Could not determine a use case where plugins would need to capture internal events.
