### ISSUE TITLE
Manually specify request parent

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#336]
Currently the only way to set the parent for a request is to modify the `request_context` threadlocal.

Should we support specifying an alternate parent ID when using the `SystemClient`? Specifically should we modify `_construct_bg_request` to accept a `_parent` kwarg?

We should definitely continue doing what we currently do, this would be more of an override.

**Comment by loganasherjones** [comment]
Hmm, I'm not sure I understand why someone would do this, but I don't see any reason not to support it. One thing that wouldn't be great is if  you set a `_parent` that is already complete, we will error on that (as we should).

**Comment by hazmat345** [comment]
From what I can tell the use-case is a standalone script that is using a `SystemClient` to do multiple things, and subsequent requests should logically be children of a request that happens earlier in the script. But since the later requests don't actually occur during processing of the initial request they are top-level.

I agree - I'm not opposed to adding this since it's pretty easy to implement, doesn't really *break* anything, and it's actually possible to implement yourself already if you manually set the `request_context` (that's just gross).

I do think this is a "you should know what you're doing" type of feature - if you're using it you should understand that the failure case you mentioned is a possibility and account for it.

**Comment by hazmat345** [comment]
Would it be better to do this:

```python
request = client.foo(bar="a", _parent=parent_request)
```

or 

```python
request = client.foo(bar="a", _parent_id="1234")
```

**Comment by TheBurchLog** [comment]
@hazmat345 What happens when the parent id does not exist, do we currently support orphans?

In v3, if we don't support orphans, we should consider it. The parent of the request could be in another namespace. So it is a valid use case to have an orphan, with the hope that a parent is out there.

**Comment by loganasherjones** [comment]
@hazmat345 my vote is the `_parent_id` just because its more flexible.

@TheBurchLog if we allow invalid parent ID's then it's going to be tricky to know what the "obvious and right" thing to do is when we go to clean up a request.
