### ISSUE TITLE
System / Command model changes

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#343]
I'd like to change the definition of the System and Command models.

I'd like to make the Command model an EmbeddedDocument that's wholly a part of a System. So the relationship would be analogous to Commands and Parameters.

#### Pros
This would drastically simplify a lot of the code that deals with creating and saving systems and commands. It would allow / require us to remove the system reference from the Command model, which is something that requires us to jump through a lot of hoops (Mongoengine does not support bidirectional references very well, so we have to save the system with no commands, set the `system` field of each command and save it, and then set the `commands` field of the System and save it again).

Updating commands also becomes drastically simplier as it's just a field replacement - we don't have to iterate over everything in order to keep IDs the same (sidebar - I don't thing we're doing this correctly right now anyway. We assume a command is the same if the name is the same. So a command that changes its parameters will keep the same ID, which I think is not correct) and then remove any orphan commands.

It also removes a very nasty class of bug that's been present for a long time - if there ever are any orphan commands in the database (commands with a `system` field that's a reference to a System that no longer exists) then the `/api/v1/commands` endpoint will return an error as the serialization fails.

#### Cons
We can't refer to a command by ID anymore. This isn't so much of a problem for us as the UI already doesn't use that anymore (it finds commands by searching the correct system).

We'd also need to provide a migration path for the database. Dropping the system, command, and instance collections would be a quick and dirty way to accomplish this, but we could work up something cleaner.

The real problem is that `/api/v1/commands/ID` is part of the v1 api. If we make this change we're not going to be able to support that at all.

**Comment by TheBurchLog** [comment]
I believe this ticket is OBE
