### ISSUE TITLE
Docker plugin startup

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#36]
We should have an easy way to allow a plugin to wait for the beergarden environment to come up. Right now trying to put a plugin in the same compose file as the rest of beergarden fails since the initial attempt to talk to brew-view fails.

**Comment by hazmat345** [comment]
@loganasherjones is this even worth keeping open? I'm not sure this should be our job? (I think I remember you saying something similiar)

**Comment by loganasherjones** [comment]
Yes, you can just set restart to true. We currently don't have a strategy for disaster recovery for plugins.
