### ISSUE TITLE
Allow Unsanitized Output

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#360]
*Editor's Note*: This ticket was original to add the unsanitized output capability. Now that it's been added this ticket tracks the additional potential features related to this:

We'd probably want to make it an explicit thing at plugin client creation:
```python
@command(output_type="HTML", unsanitized=True)
```
Also potentially an extra toggle or something in the UI.

Another possibility would be to have another `output_type` or flag on the request that would tell the UI to not bother rendering the output at all, but that it should redirect the viewer to another page (potentially after confirmation that the user does want to go to the new page).

~And we'd most likely want an application-level config to enable / disable this completely, similar to `allow_unsanitized_templates`.~ This was addressed by #592.

**Comment by hazmat345** [comment]
@TheBurchLog we have some people that would benefit from this. We should think about what it would take to support this fully.

**Comment by hazmat345** [comment]
This issue should probably be renamed?

**Comment by scott-taubman** [comment]
Unlikely to tackle this in the current iteration of BG.  Closing for now.
