### ISSUE TITLE
Yaml plugin configuration file

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#364]
I think we should support a `beer.yaml` file. 

The current `beer.conf` file is parsed as Python, which is not expected, and not really necessary for the majority of cases.

Obviously we shouldn't drop support for the current `beer.conf`, but I do think we should prefer the yaml version once it's viable.

**Comment by TheBurchLog** [comment]
What cases would parsing the beer.conf as python be required?

**Comment by hazmat345** [comment]
I can't really think of any. I think I remember that we went down that path because that's what Python itself does with `setup.py`, but I don't think we really need the same amount of flexibility.
