### ISSUE TITLE
Expose Beergarden infrastructure to Plugins

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#367]
It would be really interesting if we could make some slice of the DB that Beer-garden is using available to Plugins.

The same would apply to the message queue that Beer-garden is using.

The thrust here is that Beergarden has a dependency on
1. A message queue
2. A database

Since those are guaranteed to be present in the environment it would be interesting to make connection information and credentials easily accessible to Plugins.

This would free plugin developers from having to worry about standing up their own database or queue and would let them piggyback on whatever Beergarden is already using.

**Comment by TheBurchLog** [comment]
How would remote plugins work in this scenario? I could see opening up an HTTP Entry Point for Plugin DB interactions. That way they don't have to worry about the connection classes.

Considerations:
* Should two different plugins be able to connect to the same database objects?
* Should plugins be locked into a plugin only area of the database?
* Can Plugins read any data from the database? Users/Connections/etc?
* Currently the DB layer requires the object to be a valid Model class, how would we enforce this with externally defined objects?

**Comment by scott-taubman** [comment]
This isn't a thing we're going to explore any time soon.  Closing.
