### ISSUE TITLE
Command attributes as parameters

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#369]
It's a fairly common pattern to be able to represent the same data in different formats based on what the user wants. It would be useful to be able to mark a `@command` as having an output type that's basically a parameter. This would need to be a deliberate choice by the plugin developer as the plugin would need to be written in a way that supports it (inspecting the `output_type` and constructing the output appropriately).

It would also be nice to be able to set the command type (INFO vs ACTION) as a parameter.

**Comment by TheBurchLog** [comment]
A potential way to implement this could look like the following

```python
@command(output_types=["JSON", "HTML"], output_type="JSON")
```

**Comment by hazmat345** [comment]
OBE.
