### ISSUE TITLE
Better error when failing to connect to rabbitMQ mgmt interface

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#38]
When bartender attempts to connect to the RabbitMQ management interface during startup, the error it logs is that it's trying to connect to RabbitMQ. This is confusing and we should be more explicit about what service we're trying to connect to.

**Comment by hazmat345** [comment]
Should be be trying both on startup? Since we actually need to be able to connect to both it might be a good idea.

**Comment by loganasherjones** [comment]
I think we are trying to connect to both, but I'd have to check.

**Comment by hazmat345** [comment]
Right now we're only trying to connect to the management interface. I'm gonna go ahead and also try to connect to the actual message interface.

**Comment by hazmat345** [comment]
Addressed by https://github.com/beer-garden/bartender/pull/15
