### ISSUE TITLE
Choices request type

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#399]
It would be helpful to add a "Choice" request type. That would allow us to prune those requests very quickly and would allow an additional toggle on the requests index page to hide those requests.

**Comment by hazmat345** [comment]
So this would be useful, but it might be nicer to just know when a request is being created as a choice source, and then be able to alter retention time based on that context.

**Comment by TheBurchLog** [comment]
The recommendation is to utilize the Request type of TEMP. This will return back the results, and then delete the Request from the database.
