### ISSUE TITLE
Better error handling on system / command / request page with no resource ID

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#4]
Going to 

localhost:2337/systems will take me to the landing page
localhost:2337/systems/ takes me to the system_view page, but with no system loaded

Maybe it's not a huge deal, but it is kind of confusing if you go to systems/ when you really meant to go to the landing page.

**Comment by aamccaslin** [comment]
Move to https://github.com/beer-garden/brew-view/issues/3

**Comment by hazmat345** [comment]
Behavior as of 4/18/18:

Going to :2337/systems and :2337/systems/ now both return a 404 page. This is the correct behavior - that URI is not part of our REST api. To make it a valid Angular route it must have #!.

All of these direct to the landing page, which is what we expect:
:2337/#!
:2337/#!/
:2337/#!/systems

:2337/#!/systems/ does still route tothe system view page, but there is no system id so there's no data. This behavior is the same for :2337/#!/requests/, and going to :2337/#!/commands/ gets you stuck on the loading screen.

**Comment by hazmat345** [comment]
This needs to be fixed for good.

**Comment by hazmat345** [comment]
This is still an issue, we don't handle this case very gracefully.

**Comment by TheBurchLog** [comment]
It works
