### ISSUE TITLE
Use GridFS to handle large output

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#407]
Mongo does not allow storing documents larger than 16MB, so any output larger than that currently causes the request to fail.

It would be nice to transparently use GridFS to make outputs larger than 16MB work.

This comes from #308.

**Comment by TheBurchLog** [comment]
I was thinking about how this would work. On the save for the object we could push the output to a FileField() object. This will tell the MongoEngine to use GridFS.

```Python
    output_large = FileField(required=False)
...
    def save(self, *args, **kwargs):
        self.updated_at = datetime.datetime.utcnow()

        if self.output and len(self.output.encode('utf-16')) > (1000000 * 16):
            self.output_large.put(self.output)
            self.output = None

        super(Request, self).save(*args, **kwargs)
```

The issue I have is what to do on the read to convert it back within the Mongo Model.
