### ISSUE TITLE
Hidden command

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#414]
It would be very useful to have some way to prevent commands from being displayed in the main command listing for a system in the UI.

The use-case for this would be for commands that are purely for generating dynamic choices options.

It's related to #399 and #269, but not quite the same.

**Comment by hazmat345** [comment]
I think having commands where the name starts with a leading underscore be hidden would be a good way to start on this.

**Comment by hazmat345** [comment]
Is this done already?

**Comment by TheBurchLog** [comment]
I believe this is not done for the Requests page.

**Comment by west270** [comment]
This has been done for the system page but not the request page.

**Comment by TheBurchLog** [comment]
This would require the following:

* Adding Hidden field to Requests
* Checking command for hidden field at Request build
* Adding hidden field to indexes for Requests
