### ISSUE TITLE
Choices command source complex response

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#416]
Right now the `command` source for dynamic choices is kind of limited. The response must be in one of two forms:

```python
['value1', 'value2', ...]
[{'value': 'value1', 'text': 'Value 1'}, {'value': 'value2', 'text': 'Value 2'}, ...]
```

In the second form the item keys *must* be 'text' and 'value'. It would be useful to be able to specify alternate keys.

The use-case here is an external system or a command that already returns a list of dicts in an alternate form. This feature would make it unnecessary to create another command just to 'translate' the response into the specific form the dynamic choices system is expecting.

This is low priority because a workaround already exists.

**Comment by scott-taubman** [comment]
Hard to imagine us tackling this at this point.  Closing for now.
