### ISSUE TITLE
Choices with no type specification

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#42]
The following does not validate in our GUI:

```python
@parameter(key='x', choices='some_command()')
def foo(self, x):
    pass
```

**Comment by hazmat345** [comment]
This is going to be a little tricky - we need to basically combine the raw and dynamic-choices parsing and validation.

Doing this correctly in ASF land is going to take a little bit of refactoring so we need to decide if it's worth the effort. If someone just forgot to specify a type we should maybe fail at compile time ('sorry, you can only use strings or numerics as choices'). If someone actually wants to be able to use variant-type choices:

```python
@command
def some_command(self):
    return ['"string"', 1, null, 4.5]

@parameter(key='x', type="Any", choices='some_command()')
def foo(self, x):
    pass
```

Then we should support it, but it's not a quick fix thing.

**Comment by hazmat345** [comment]
Ok, here's where I think we should land on this:

* Nobody is asking for `Any`-typed choices. That would be a *major* pain to do with the angular UI, so we shouldn't bother with that.
* Disallowing `Any`-typed parameters at decorator validation time is tempting, but that boils down to restricting a brewtils capability based on the angular frontend limitations, which I'm not OK with.

I believe this should be tracked against the react UI to attempt to add support there.

**Comment by scott-taubman** [comment]
Unlikely to tackle this in the current iteration of BG.  Closing for now.
