### ISSUE TITLE
Actual Dynamic Choices

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#43]
We need to be able to express choices that are basically 'static' but aren't known until runtime.

Basically, provide the ability to modify choice sources at runtime. We specifically need to target modification when new Instances come up, but we should probably support the more general case.

Two use cases driving this:

1. A list that can grow as new instances are added.
2. A dictionary that uses the instance name as the key into the choice list. New instances would add themselves to the dictionary as they come up.

To support case 2 we probably also need to also do some work with allowing the instance_name field to be used as an input to a dynamic choice field.

**Comment by loganasherjones** [comment]
This is already supported. Perhaps caching should be added at a later date. Until then, I'm closing this issue.
