### ISSUE TITLE
Allow Plugin.client to be changed

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#483]
Started by beer-garden/brewtils#206

With the restriction on not modifying a client once it's set it's possible to get into a state where an "invalid" client is set and not able to be changed.

Seems like disallowing client changes might be problematic.

If we *do* allow switching clients then I think we need to account for the case where the system name isn't resolved from the config and the client decorator doesn't have one either:

```python
            #self._system.name = getattr(new_client, "_bg_name")
            self._system.name = getattr(new_client, "_bg_name", None)
        if not self._system.version:
            #self._system.version = getattr(new_client, "_bg_version")
            self._system.version = getattr(new_client, "_bg_version", None)
```

**Comment by hazmat345** [comment]
Not sure why this was in Done, I don't know that it's been addressed.

**Comment by TheBurchLog** [comment]
@hazmat345 What would be the impact if we allowed this.

**Comment by TheBurchLog** [comment]
There isn't a real good reason to support this at the moment, so we can close this and reopen a new ticket when we have a more thought out idea.
