### ISSUE TITLE
Namespace-less requests Pour It Again

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#515]
Upgrading from v2 to v3 will result in existing requests not having a namespace. This breaks the Pour it Again functionality. We need to determine what to do / how to handle.

**Comment by TheBurchLog** [comment]
@hazmat345 

When a plugin is initialized and does not have a Namespace it requests it from the Garden. The Garden will then default that namespace to the Garden Name. With this in mind, should we default Pout it Again to the same functionality? If a namespace is not provided when attempted to redo the command, grab the local garden information and use that?

**Comment by hazmat345** [comment]
This was fixed by #536, but I'm leaving it open as it should be fixed on the backend, not the UI.

**Comment by hazmat345** [comment]
This is OBE - creating a request with no namespace will default to the garden name.
