### ISSUE TITLE
Request view incorrect status

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#516]
I've seen this a couple of times... when I create a new request the request page comes up with the correct output but the status is `IN_PROGRESS`. It looks like there's another http request being made to retrieve the request again... guessing that's generating a race condition with the websocket event handler.

**Comment by TheBurchLog** [comment]
@hazmat345 
Can you verify that this is still occurring and document how I can recreate it?

**Comment by hazmat345** [comment]
At this point I'm guessing this is just another expression of #627, so I'm going to close this.
