### ISSUE TITLE
Role Based Filter

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#530]
To add additional complexity to our platform, let's investigate how to implement role based filter. The primary use case is filter Namespaces by roles. That way users can be segmented by different focus areas of plugins. Target audience is someone who 10+ children connected that don't want to overwhelm their users.

My initial concept was to create a new permission field that is mapped to all known namespaces. We will need an admin command to rebuild this permission mapping based off what is the in the database.

Then if the System Admin sets a flag in the config to restrict user access based on Namespace. 

If a user wanted to see the systems in the namespace, they would need both `bg-system-read` and the namespace.
If a user wanted to see the requests for a namespace, they would need both `bg-request-read` and the namespace.

The big issue I see is how do we handle when a plugin invokes something in a different namespace that they don't have access to. So we would have to add logic to allow them to see child requests if the parent is within their permissions. OR, we could restrict their access and not allow them to see the children. We would need a smart way to say it has children but you can't see it.

To accomplish this on the backed we should create an annotation that filters the response before sending it out. Checking the model type to see if we have a filtering function set for it. We can set this on the endpoints that need filtering.

Actions to Accomplish:
- [x] Remove Nested roles and Reduce Permissions
- [ ] Add Namespaces to Roles
- [ ] Implement generic Entry Point Annotations
- [ ] Add Entry Point inbound filtering on Namespaces
- [ ] Add Entry Point outbound filtering on Namespaces
- [ ] Dynamically add Namespaces seen in environment
- [ ] Delete Namespace Role Property

**Comment by scott-taubman** [comment]
We're tracking the auth effort slightly differently now, which makes this issue OBE.
