### ISSUE TITLE
Standardize config "enabled" vs "enable"

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#531]
Need to decide if we're using "enabled" or "enable" in config item names.

**Comment by TheBurchLog** [comment]
My vote is for `enabled` because it is an adjective and describes the state of that property.

**Comment by west270** [comment]
@hazmat345 
My vote is for enabled as well, I agree with @TheBurchLog reasoning.

**Comment by hazmat345** [comment]
That sounds good tom. Unless there are objections I'm going to apply that to all config names, and it should be A Rule going forward (no verbs, just nouns).

**Comment by TheBurchLog** [comment]
@hazmat345 Got for it!
