### ISSUE TITLE
Auto-reload plugin logging config when file changed

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#532]
Right now we have an API endpoint for reloading the plugin logging config. This seems fairly unnecessary - if the plugin logging config file is changed then it's almost certain we'd want to use it immediately without having to hit a REST endpoint to kick it.

We should think about watching the file and reloading the config whenever it changes (assuming it passes validation).

The other option here is to add an endpoint that will actually allow for updating the configuration directly.

**Comment by TheBurchLog** [comment]
Which logging configuration are you talking about here
1. Beer Garden Logging Config
1. Local Plugin Logging Config

If we are talking about auto reloading the Local Logging config, then I agree with you. That way a system admin can go in and update the file and without having to reload the plugin.

If we are talking about the Beer Garden Logging config, I would be nervous to auto push that out. We had discussed having different levels of logging configs in #525. So if we are doing this logging config, it would only be applied to plugins that don't have logging in the database or local.

**Comment by hazmat345** [comment]
The `plugin-logging.yaml` file is the one I'm talking about. You should be able to use `watchdog` to set up a little file watcher thing. I'll need to be set up in the main app and the entry points, I think.

**Comment by TheBurchLog** [comment]
@hazmat345 
Here is my thought on how to get this working properly. Once BG successfully validates the new logging config, BG requests all "local" plugins to re-initialize their logging configuration. That way each plugin will do their own internal checks to determine if they need the remote logging configuration. That way it removes the logic off of BG proper. 

This will probably need to be a new Admin command that requests `_initialize_logging` to be ran.

**Comment by hazmat345** [comment]
I'm not opposed to that, but you're going further down the path than what this ticket is meant to address.

Right now, the application will read `plugin-logging.yaml` on startup and keep it in memory. Whenever a plugin comes up it will ask beer-garden for a logging configuration. The application won't re-read the file, it'll just hand the plugin what it already has in-memory.

This ticket is meant to just address what should happen if that file is changed while the application is running. Currently, nothing happens automatically. Any plugins that ask for a config will still get the version that was originally loaded during startup.

There's currently a REST endpoint you can hit that will cause the application to re-load this file. However, it's annoying because that endpoint isn't exposed anywhere in the UI, only in the swagger docs. Once you hit that endpoint the application will re-load the file and any new plugins that ask for a configuration will get the new one.

This ticket is only to remove that last part, not to automatically push anything to the plugins.

**Comment by TheBurchLog** [comment]
@hazmat345 
I was thinking it was going to be the whole process of reload and push. I am working on integrating it into the main App.py process and I got the stub outs for pushing these updates to the plugins.
