### ISSUE TITLE
Consolidate Systems and Queues admin pages

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#533]
We should consolidate the queue admin page functionality into the system admin page:

- See how many messages are on a specific instance's queue*
- Clear a specific instance's queue
- Clear all queues

* We should make this functionality require an affirmative action rather than just passively being update every couple of seconds. Getting the message counts for all queues is a resource-intensive operation for the rabbit broker, so we shouldn't be doing it all the time for every user on the admin page.

**Comment by TheBurchLog** [comment]
@hazmat345 
Thinking about how we could handle this. If we placed a big red button to clear Queues next to the Rescan button. Then in the new hamburger dropdown we could add a function to clear the instance queue. We could also add a function to pull the instance queue information in a popup with the option to clear it.

**Comment by hazmat345** [comment]
That sounds good to me, more items for the hamburger dropdown.

**Comment by TheBurchLog** [comment]
We will get all of the things in the hamburger :smile:
