### ISSUE TITLE
Navigation Menu

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#534]
It is super annoying when you are in an admin area to have to navigate through the menu to find another admin page. Should we default to the Admin section when on an Admin page?

**Comment by hazmat345** [comment]
I'd be OK with putting Admin back up on the main nav bar. It's been annoying me too :smile:

**Comment by TheBurchLog** [comment]
I am going to leave the Themes option as a sub menu, but moving the Admin back up will be nice. Ill get that updates shortly.
