### ISSUE TITLE
Graceful stopping with SIGTERM

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#548]
If I run the application using the `bin/app.sh` script and then later attempt to `kill process_num` the local plugin processes don't seem to shut down gracefully. The manager goes through and sends `SIGKILL` for each of them but that's not great.

**Comment by hazmat345** [comment]
OK, I did a bunch of research on this, and I think my ultimate decision is to not fix.

This was a very helpful resource: http://www.andy-pearce.com/blog/posts/2013/Aug/process-groups-and-sessions/

The reason this is failing is because we aren't doing anything special to spawn the local plugin processes in a separate process group from the main beergarden process.

When you run the app as a service, or in pycharm, or even run the script in the shell and keep it in the foreground the shutdown signal is sent to all processes the process group. The plugin processes catch the signal and shut down in an orderly way.

However, when you run the script in the background and then `kill` it, the signal is only sent to that specific process. By convention, the process group leader PID is the same as the process group id. But the beergarden process is actually a child of the `app.sh` process, so the correct process group ID will be the beergarden process parent ID.

You can send a signal to a process group by negating the ID, and add the `--` so it's not interpreted as a flag:

```
kill -- -1234
```

If I could figure out a way to successfully spawn the plugin processes in their own group (so they don't automatically get the signal) then we could always do that, and then have the plugin manager signal them whenever *it* sees the signal. Until then that won't work because there's no way to tell if we *need* the plugin manager to manually signal the processes - if we're operating in an environment where the signal is already caught we definitely don't want to send *another* one.

**Comment by hazmat345** [comment]
Keeping this open as there may be improvements to be made here.

**Comment by TheBurchLog** [comment]
When you kill a locally running plugin by `kill <pid>`, Beer Garden restarts the plugin. So this looks to have been resolved. The shutdown process was successful as well.
