### ISSUE TITLE
Node 8.3.0 Issue?

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#6]
Error: Cannot find module "eonasdan-bootstrap-datetimepicker" when using node 8.3 and npm 5.4.2

**Comment by aamccaslin** [comment]
Also getting Error: Module build failed: Error: ENOENT: no such file or directory beer-garden/brew-view/brew_view/static/node_modules/babel-polyfill/lib/index.js

Switching to a previous version of node and using yarn install was a work around

**Comment by hazmat345** [comment]
At this point because of how we're installing an old bower dependency you *have* to use yarn to do the install.

I tested using node 8.3 / npm 5.4.2 and was able to do the build.

**Comment by hazmat345** [comment]
The bower dependency is now on npm. I just tried installing with node 8.3 and npm 5.4.2 and everything worked, so closing this as OBE.
