### ISSUE TITLE
Command-based choices on a child garden

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#639]
Validation for the choices does not go through the router, so this is not going to work.

**Comment by TheBurchLog** [comment]
@hazmat345 
What are your thoughts on if a plugin in a Parent garden utilizing a command located on a Child garden? I think this should be allowed.

**Comment by hazmat345** [comment]
@TheBurchLog I agree. I think this is an easy fix - the validator needs to construct an `Operation` instead of just calling `process_request` directly.
