### ISSUE TITLE
File Based Triggers

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#647]
Create new Trigger that executes against file changes on the local directory of host system for Beer Garden. This should operate similar to how local logger file is reloaded.

We should expose file parameters as valid input. Similar to how we inject variables for local plugin logging.

- `$file_name`
- `$src_path`
- `$file`

**Comment by TheBurchLog** [comment]
This will probably be impacted by this other ticket: https://github.com/beer-garden/beer-garden/issues/368

**Comment by hazmat345** [comment]
Hmm, not sure why this wasn't closed by the PR.
