### ISSUE TITLE
Multiprocessor BaseManager Ideas

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#704]
For local plugins, why should they make a REST connection back to the server that they are hosted on. If we wanted, we could look at something like Base Managers as an option to give them access to the Router class to ask things directly. I am not sure what that would open our framework up to, could create some nefarious actions this way because it would bypass our authentication and someone writing a plugin could technically tap into that (which they could do now if they know our object schema so what the heck). 

If I was to implement this, it would be a new Entry Point and potentially have a limited number of router options it could do, like no local admin actions (users/gardens management). 

https://docs.python.org/2/library/multiprocessing.html

**Comment by hazmat345** [comment]
I'm not sure what benefits we would get from doing this?

**Comment by hazmat345** [comment]
Adding needs discussion so we can talk about this, but probably recommend closing.

**Comment by scott-taubman** [comment]
I think I'm just going to close this one.  Long term I think we want to reduce (possibly eliminate) the distinction between local and remote plugins, rather than increase it.
