### ISSUE TITLE
Date-based jobs are running immediately

### ISSUE THREAD

**Issue by SpecificallyGravity** [beer-garden/beer-garden#722]
When scheduling a new job, those with date-based triggers are being run immediately and then deleted (due to APScheduler logic).  This is because the `next_run_time` is defaulting to the current time.

**Comment by SpecificallyGravity** [comment]
A quick fix can be implemented to add logic for `jobstore.py` in `construct_job()`, but this causes the UI to display an incorrect next run time. 

Example Logic:
`    if job.trigger.run_date:
        next_run_time = utc.localize(job.trigger.run_date)
    else:
        next_run_time = utc.localize(job.next_run_time) if job.next_run_time else None`

**Comment by TheBurchLog** [comment]
I am going to take a look at this and see if I can figure out anything else.

The primary issue is that `next_run_time` is getting set by default to the current time stamp. So we have to figure out what is setting that timestamp.
