### ISSUE TITLE
Double Events from Child

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#736]
We noticed that Children were sending double events when a Request was created on the child. This doesn't break any functionality, but it does create a race condition where if the Request Create is not saved before the second Request Create is processed it will throw an error message for conflicting IDs.

**Comment by hazmat345** [comment]
@TheBurchLog is this title and description still accurate? From #746 it seems like the real problem is duplication handling of the same event.

**Comment by hazmat345** [comment]
Closing as OBE.
