### ISSUE TITLE
RabbitMQ admin API SSL certificates

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#74]
We should support secure connections to rabbit.

**Comment by hazmat345** [comment]
What do we want the default to be when trying to connect? Secure or non-secure?

**Comment by hazmat345** [comment]
Also, pika seems close to version 1.0, and it looks like they've reworked their SSL stuff. We might need to wait for that in order to fully support everything we want to do.

**Comment by loganasherjones** [comment]
Yeah, I'm almost in favor of removing pyrabbit as a dependency and just rolling our own. This would be better long run (since we want to be able to support multiple message delivery services) I don't super care about waiting for pika 1.0, hopefully it'll beat us.

**Comment by hazmat345** [comment]
The pyrabbit maintainer accepted my PR and cut a new release, so we aren't blocked by that anymore.

**Comment by hazmat345** [comment]
There are several PRs in for this issue. Couple of things:

- I'm going back and forth on the best way to deal with the fact that adding SSL options for both the pyrabbit and pika connections in bartender means that we we have three 'ssl' sections in the spec / config. I made a little `specifize` function in bg-utils that allows for one 'base' ssl section that individual sections can override.
- Both local and remote plugins work, but I'm not sure exactly how, which makes me nervous. I'm worried that pika might not be properly validating the server cert when using `SelectConnection` (the async callback-based option). Using `BlockingConnection` (what we use to publish messages from Bartender) works as expected.
