### ISSUE TITLE
Plugin process default signal handler for SIGTERM

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#745]
It might be nice to add some sort of default signal handler for SIGTERM in the Plugin `_startup`. We currently only break the run loop on a SIGINT since that gets translated to a raised `KeyboardInterrupt`, which we then handle.

I realized this when updating the docker-compose plugins file when I noticed that the containers were not shutting down gracefully when running `docker-compose stop`. After looking into it it's because the default behavior of docker-compose is to send a SIGTERM, which doesn't do anything to our plugin containers.

It's possible to fix this for our specific case by setting the `stop_signal` option in our compose file (which I did in a368a961) but I wonder if handling SIGTERM is something we should do by default.

We would for sure need to provide a way to disable this behavior if we decide this is something we're interested in.

**Comment by TheBurchLog** [comment]
@hazmat345 Can you do some market research on this to see if people care.

**Comment by hazmat345** [comment]
After thinking about it, I don't think people will care. I definitely don't think people will care enough to not do this. People expect SIGTERM to end a process gracefully, which is what the PR does.

In the PR for this I save off the previous SIGTERM handler and do the switch in the `__init__` method. So it's at least possible for someone to revert the behavior if they actually care:

```python
def main():
    plugin = Plugin()

    signal.signal(signal.SIGTERM, plugin._sigterm_orig)

    plugin.run()
```

**Comment by hazmat345** [comment]
After looking at #770 I'm concerned that this might cause problems with the plugins. Need to investigate.
