### ISSUE TITLE
Use v3 brewtils with v2 Garden

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#751]
It would be great if plugins using v3 brewtils could work with a v2 garden.

**Comment by TheBurchLog** [comment]
Lets get only an early release of V3 working with V2. Once we hit v3.1 of Brewtils this will no longer be supported.

**Comment by hazmat345** [comment]
We should probably be "correct" about this then... hit the server `version` api early and log a deprecation warning that this capability is going away (or at least, won't be officially supported for long).
