### ISSUE TITLE
Wait for Garden connection during plugin creation

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#758]
Should we be blocking during Plugin creation until the Beer-garden connection is successful? Consequence of *not* doing this is that any `SystemClients` that are expecting the namespace to be correct may not actually be.

We could also just raise if the connection fails. I'd prefer not to do that, though.

**Comment by TheBurchLog** [comment]
Plugins are now required to connect and if it doesn't then the plugin fails.
