### ISSUE TITLE
Unique name for SystemClient

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#76]
SystemClients should have a public property with a unique name. Currently you have to reference hidden attributes to get the system name / system version / instance name, and that's not ideal.

**Comment by loganasherjones** [comment]
related to #279

**Comment by hazmat345** [comment]
https://github.com/beer-garden/brewtils/pull/273 addressed the hidden attributes issue.

Still remaining is the "unique name." I don't want to add another attribute / property, I think this should be handled by defining `__str__`.
