### ISSUE TITLE
Origin Garden for Operations to prevent circular processing

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#766]
To help with future proofing of Beer Garden, we should look at how to prevent circular operation forwarding. This has a higher chance of happening as we expose more entry point configurations. 

If we add `original_garden_name` to the Operation object, then we can do a check on the operation prior to routing.

```
if operation.source_garden_name != local_garden_name and 
   operation.original_garden_name == local_garden_name:
    raise Exception ("Circular Beer Garden Configuration, unable to process 
                                operation because this Garden created the original")
```

The same thing should be applied to Events. That way we don't process events from a child Garden that was generated on the local Garden.

**Comment by hazmat345** [comment]
This is OBE - Operation models now have a `source_garden_name` field.
