### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#782]
We need to migrate all actions from Travis-CI to Github Actions.

**Top Priority Repos:**
- [x] Brewtils
- [x] Beer Garden
- [x] Angular Schema Form Builder
- [x] Angular Schema Form Add Ons

**Second Priority Repos**
- [x] Beer-Garden.io
- [x] Example Plugins
- [x] Brewview
- [x] Bartender
- [x] BG-Utils

**PR Based Actions:**

- [x] Linting
- [x] PyTest
- [x] Coverage

**Release Based Actions**
- [x] PIP Deploy
- [x] RPM Builder
- [x] Docker Builder

**Comment by TheBurchLog** [comment]
Form Builder PR: https://github.com/beer-garden/angular-schema-form-builder/pull/15

**Comment by TheBurchLog** [comment]
Got lazy and stopped marking all of the PRs. I think it is all done. Going to leave this open until we do our next release.

**Comment by hazmat345** [comment]
Forgot we had an issue for this.

3.0.4 release made it through docker build / publish successfully, but died on the rpm build. 3a5dd9a0 will hopefully help with that, but there are still `${{ github.ref }}` lines that I think will cause problems.

**Comment by hazmat345** [comment]
@TheBurchLog I think this is done! 😄
