### ISSUE TITLE
Support for client Certificate and key in separate files broken

### ISSUE THREAD

**Issue by astephon88** [beer-garden/beer-garden#785]
The requests library supports a client certificate and key to be in separate files by passing the cert as a tuple of file path strings. Prior to brewtils 3.0, this format could be used by by setting ca_cert to the tuple when initializing a client (SystemClient, SimpleClient, or RestClient), and the tuple would be properly passed down to requests. Now, with the new Yapconf configuration loading, this tuple is getting dumped as a string, and making requests very unhappy.

**Comment by hazmat345** [comment]
Hey @astephon88, just wanted to let you know that this fix is in brewtils-3.0.1.

Thanks for letting us know about this, and please reach out if you have any issues!
