### ISSUE TITLE
Local Plugin logging

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#787]
Need to investigate plugin logging when the plugin suffers a catastrophic error. The logs appear to be missing in this scenario:

- Local plugin
- CAPTURE_STREAMS=True
- Plugin creation is first line, completes successfully
- Plugin immediately raises a RuntimeError

The resulting error and stacktrace can be see if running this plugin as a remote plugin in a terminal, but the logs don't appear to be in any of the "expected" locations when running as a local plugin under a systemd Beer Garden.

**Comment by hazmat345** [comment]
The issue here is that the RuntimeError (and stacktrace) are being logged to stderr. This makes sense as the exception is uncaught, so Python is just doing what it can.

Doing this is better (in that it logs to the correct place), but annoying:

```python
def main():
    plugin = Plugin(...)

    raise RuntimeError("Whoopsie")


if __name__ == "__main__":
    try:
        main()
    except Exception as ex:
        logger.exception(ex)
```

**Comment by hazmat345** [comment]
Aha... looks like `sys.excepthook` is what I want.

**Comment by TheBurchLog** [comment]
@hazmat345 This was something I was running into the other day. Let's hope this fixes the issue.
