### ISSUE TITLE
304 Status on config and commands

### ISSUE THREAD

**Issue by aamccaslin** [beer-garden/beer-garden#8]
Trying to access the server and going to /#!/commands will give give 304 status and the loading wheel indefinitely.  Accessing the server at api/v1/commands will give a 200 status and load all of the response headers that didn't load before such as "Content-Type" and "Content-Length"

**Comment by aamccaslin** [comment]
Moved to https://github.com/beer-garden/brew-view/issues/5

**Comment by hazmat345** [comment]
Not sure why I reopened this. Can't replicate.
