### ISSUE TITLE
Scheduler Not Rendering Trigger Form

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#819]
Somewhere between the 3.0.0 and 3.0.4 releases a dependency was updated that has caused the scheduled page to no longer work. This can be seen in both our RPM and Docker artifacts. This wasn't noticed at first because no one ever runs `npm install`....

What we know:
The Scheduler renders two forms, Request and Job. When the HTML condition is sastifified for the Job form to be displayed, nothing is returned. We can see that the `$scope.jobModel` is not populated by looking at the preview box on the right. 

I have attempted to reload the Request Form in the Job's place in the HTML and I got the same result. So it appears to not be an issue with how we are formatting the sf-form values. 

Now we have to figure out which package changed to resolve this....

**Comment by hazmat345** [comment]
I just did a clean install (removing `node_modules` first) on [3.0.1](https://github.com/beer-garden/beer-garden/tree/3.0.1) and I see the broken behavior.
