### ISSUE TITLE
Alias systemd control of beer-garden service

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#820]
It's been requested that we include a little helper utility I wrote for my own use in the actual rpm:

```sh
#!/bin/sh

sudo systemctl $1 beer-garden
```

It turns this:

```
sudo systemctl restart beer-garden
```

into this:

```
beer restart
```

Although maybe it should be `beerctl` instead of `beer`?

**Comment by TheBurchLog** [comment]
This should update the post_install script add this, and the uninstall script to remove it.
