### ISSUE TITLE
Add descriptions to systems admin page

### ISSUE THREAD

**Issue by west270** [beer-garden/beer-garden#840]
Adding descriptions to systems admin will allow users to see the description without navigating to new page.

**Comment by west270** [comment]
![image](https://user-images.githubusercontent.com/61320354/105401759-85cec300-5bf4-11eb-85eb-27d49127aba1.png)
![image](https://user-images.githubusercontent.com/61320354/105401943-bf9fc980-5bf4-11eb-9c02-693448726690.png)

**Comment by TheBurchLog** [comment]
@west270 We will go with the first option, so we can ensure people can see if the description changes.
