### ISSUE TITLE
Job Schedule Button

### ISSUE THREAD

**Issue by west270** [beer-garden/beer-garden#847]
I think it could be useful to add a button for scheduling a job on the page for making request, so there would be no need to navigate through the scheduler to get to the create job page.

**Comment by scott-taubman** [comment]
Is this different from the button that appears in the top right of the command preview? See the included screenshot.

![Screenshot at 2021-07-08 12-30-29](https://user-images.githubusercontent.com/86254668/124959020-c70f2f80-dfe8-11eb-9cf3-43dd95b2f4e8.png)

**Comment by scott-taubman** [comment]
Is this different from the button that appears at the top right of the command preview?

![schedule_request](https://user-images.githubusercontent.com/86254668/124959331-18b7ba00-dfe9-11eb-9f87-b7c8803ac4a4.jpg)

**Comment by scott-taubman** [comment]
Per question above, this turned out to actually be implemented already.  Closing.
