### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#85]
We need a better way to control which versions of dependencies are used for travis tests. Ideally we'd have release branches test with the 'real' versioned packages (specifically bg-utils) and the develop branch test against the current develop bg-utils branch.

This would be OBE (I think) if we removed bartender.

**Comment by loganasherjones** [comment]
Yes, I think this would also be OBE if we were using git flow.

**Comment by hazmat345** [comment]
I believe this is now OBE. Closing.
