### ISSUE TITLE
Automated Request Generator

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#858]
We need a way to generate large amounts of Requests for stress testing.

**Comment by TheBurchLog** [comment]
Just thinking about this, we could use the `/forward` API. We can make a bunch of canned Request objects, then create random UUIDs for them. Now we don't have to wait for the plugins to actually run, just for the API to save them

**Comment by TheBurchLog** [comment]
Completed, we now have JMeter setup to auto generate requests for stress testing. The pipeline can also cache the requests to simulate a large database.
