### ISSUE TITLE
Stomp entry point always running

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#872]
It's not currently possible to prevent the stomp entry point from starting. It needs to be possible.

**Comment by hazmat345** [comment]
We have this:

```python
if entry_value.get("enabled") or entry_name == "stomp":
   <start the entry point>
```

I remember there's a reason for that, but I don't remember what it is.

**Comment by TheBurchLog** [comment]
Stomp entry point has to be always one to enable the adhoc deployment of Child Gardens that utilize stomp as the access point. If not, we would have to monitor and then spin up STOMP and republish the Garden update event to it. This would increase the complexity and we should avoid that.
