### ISSUE TITLE
Error when REQUEST_CREATED event is received by parent

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#902]
I'm getting a strange situation where a parent attempting to handle the REQUEST_CREATED event generated by a child is logging an error. Looks like it's failing the request creation in the DB because of a duplicate ID. That doesn't make a ton of sense because the request is brand new.

I'm seeing this for requests generated on the child, not when the request originates from the parent.

**Comment by TheBurchLog** [comment]
On my first walk through the code, I don't see anything glaring that would cause this issue.

When a Child generates a Request, that event is published to the Parent record. Then we check if that Request exists in the Database, if it doesn't then the record is created. The only way I could see this error happening is if two Request_Create events are generated. Going to add some loggers to investigate.

**Comment by TheBurchLog** [comment]
Just confirmed that the Parent is processing all events twice. So now we get to figure out if two are getting sent or two getting internally published.

**Comment by TheBurchLog** [comment]
Just figured out what is going on.

The child is publishing a single event to the parent. When the parent receives the event, it publishes it to the internal queue for handling events. In a Beer-Garden that has a single Entry Point, there will be two listeners (Main and Entry Point). So this event will be processed twice by the Parent.

The only way we could get around this is if we established filtering on which events each Processor could handle. For example, the Main process can handle REQUEST_CREATE, and REQUEST_UPDATE, but all processes handle REQUEST_COMPLETE.

**Comment by TheBurchLog** [comment]
Thought about it some more, that level of complexity of filtering which processor gets which event would be a larger rework. So instead, we can just attempt to create the request and pass on the duplicate exception.

**Comment by hazmat345** [comment]
This is essentially a duplicate of #736.
