### ISSUE TITLE
Zero Annotation Clients

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#915]
With the new enhancements to the decorators in place, we are one step away from not needs the annotations at all for the most simple approach for a new plugin.

Now that we can inspect Doc Strings and inputs to dynamically add Variables for commands that were not defined, we could also do that for whole Class objects. Here is the example I was thinking of.

### Class Definition
```python

class SimplePlugin:
    """A simple plugin"""

    def __init__(self):
    """The Init"""
        pass

    def __private(self):
        """Private Function"""
        pass

    def public(self, arg1):
        """Public Function"""
        print(arg1)
````

### Client Usage
```python
Plugin(
        SimplePlugin(),
        version="1.0.0",
        **connection_params
    ).run()
```

### Expected
- System
  - Description: A Simple Plugin (Derived from class inspect)
  - Name: SimplePlugin (Derived from class name)
  - Version: 1.0.0 (Don't have a good idea on how to auto generate this)
  - Commands: (Only public functions) 
    - public
      - Description: Public Function (Derived from function inspect)
      - Input: arg1 (Derived from function inspect)

**Comment by scott-taubman** [comment]
This is something of a core tenant of the BG redesign.  It won't be tackled in this iteration though, so I'm going to close it.
