### ISSUE TITLE
Change garden endpoint routing to be less restrictive

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#940]
We're hitting an error when a garden name contains a '-'. This is the same issue as https://github.com/beer-garden/beer-garden/pull/885, but with special characters instead of unicode.

I think always urlencoding the garden name before hitting the rest api should fix this.

**Comment by scott-taubman** [comment]
After discussion, we should just solve this problem by being more flexible with the routing regex and accepting whatever is provided for the garden name.

**Comment by Jake-Ross** [comment]
I just tried out a few names with a capture-all regex. This fixes some special characters, like hyphen `-`, but there are notable exceptions:
- Forward/back-slashes `\`, `/`
- Sometimes, if `#` is in a garden name, BG defaults the connection information to localhost. Other times, it will break routing like normal.

Is the solution to allow this but block it at the UI level?

**Comment by scott-taubman** [comment]
After more discussion, regardless of where we land on the routing we should update the UI code to do the url encoding.  That's going to be needed in any case.

**Comment by jlrpnbbngtn** [comment]
Tested with all the usual ASCII symbols, but also with a mix of ASCII symbols, ASCII alphanumeric and Unicode characters. No problems found.
