### ISSUE TITLE
STOMP entry point unable to route to newly created Systems

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#949]
When deploying to a clean environment, the Router for STOMP is not being populated.

Things observed:
- The router relies on the System.py to update the routing table. This does not scale across processes
- If the router is not updated in the System.py, then there is a race condition with plugins where the plugin fails to initialize.
- Attempted to have the router `handle_event` class handle it regardless, and that didn't work.
- If you reboot Beer Garden it works as expected
- If you shutdown Beer Garden and delete the database, then start back up Beer Garden, it works as expected.
- The error message is not helpful to let the end user know that it was a routing error.
  - `2021-04-05 17:38:01,080 - beer_garden.api.stomp.transport - WARNING - Error parsing and routing message: 'docker:echo-3.0.0.dev0'`
- The STOMP entry point is receiving events from the HTTP entry point because in the Unit Tests we can publish over HTTP and capture the `REQUEST_CREATED` and `REQUEST_COMPLETED` events on the STOMP topic.

The only way I could get this to work is to add `setup_routing()` in the router.py class prior to looking up the system mapping for a `REQUEST_CREATE` (around line 550).

**Comment by TheBurchLog** [comment]
We were able to prove this happens when adding a new plugin to an environment. The STOMP entry point is not getting the updates to the routing mapping.

**Comment by hazmat345** [comment]
I think this is a consequence of going too far in #606. I reworked how system create event handling worked to fix remote plugins. I'm guessing that those changes broke the other entry points.

**Comment by hazmat345** [comment]
I think these are the steps to reproduce (haven't tested this yet):

1. Start with no systems in the database
2. Start beer-garden
3. Start a remote plugin
4. Try to create a request for that plugin using the Stomp entry point
