### ISSUE TITLE
Stomp Event Handler for GARDEN_CREATED

### ISSUE THREAD

**Issue by TheBurchLog** [beer-garden/beer-garden#956]
The Stomp Event Handler does not trigger off `GARDEN_CREATED`. This should be treated the same as `GARDEN_UPDATE`. When creating a new Garden through the API, you can pass forward the connection info. This would be helpful for anyone who wants to automate the creation of child garden connections. That way they don't have to first Create, then Update.

**Comment by hazmat345** [comment]
I'm going to close this as OBE. It doesn't look like either of the entry points assign handlers to any GARDEN event, so I don't think this is applicable anymore.
