### ISSUE TITLE
Alt env names need to be added

### ISSUE THREAD

**Issue by loganasherjones** [beer-garden/beer-garden#97]
As we have changed the configuration files for 2.4.0, we also need to add `alt_env_names` to our specifications for both bartender and brew-view.

This is necessary for backwards compatibility.

**Comment by hazmat345** [comment]
@loganasherjones any thoughts on that comment I made?

**Comment by loganasherjones** [comment]
Yeah, this needs to be an update to `yapconf`. If we are using it as a deprecation warning, then in `yapconf` I should call it `old_env_names` or something to indicate that. Really, `yapconf` just needs a better migration strategy all around.
