### ISSUE TITLE
Parse stomp headers as a list of dicts

### ISSUE THREAD

**Issue by hazmat345** [beer-garden/beer-garden#976]
This is really a yapconf problem. Our spec currently has the stomp headers as a list of strings that look like dicts. Trying to set that spec item as a list of dicts breaks yapconf pretty hard, and yapconf specifically says that's not supported.

Specifically, it looks like argparse is breaking.

**Comment by TheBurchLog** [comment]
Do we need to update yapconf or should we just live with it?
